// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmm.proto

package discussproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCMMsRequest_Sort int32

const (
	GetCMMsRequest_new GetCMMsRequest_Sort = 0
)

var GetCMMsRequest_Sort_name = map[int32]string{
	0: "new",
}

var GetCMMsRequest_Sort_value = map[string]int32{
	"new": 0,
}

func (x GetCMMsRequest_Sort) String() string {
	return proto.EnumName(GetCMMsRequest_Sort_name, int32(x))
}

func (GetCMMsRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{17, 0}
}

// DEFINITIONS
type CMMUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TwitterScreenName    string   `protobuf:"bytes,2,opt,name=twitterScreenName,proto3" json:"twitterScreenName,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMMUser) Reset()         { *m = CMMUser{} }
func (m *CMMUser) String() string { return proto.CompactTextString(m) }
func (*CMMUser) ProtoMessage()    {}
func (*CMMUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{0}
}

func (m *CMMUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMMUser.Unmarshal(m, b)
}
func (m *CMMUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMMUser.Marshal(b, m, deterministic)
}
func (m *CMMUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMMUser.Merge(m, src)
}
func (m *CMMUser) XXX_Size() int {
	return xxx_messageInfo_CMMUser.Size(m)
}
func (m *CMMUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CMMUser.DiscardUnknown(m)
}

var xxx_messageInfo_CMMUser proto.InternalMessageInfo

func (m *CMMUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CMMUser) GetTwitterScreenName() string {
	if m != nil {
		return m.TwitterScreenName
	}
	return ""
}

func (m *CMMUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CMMUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type CMMLink struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Site                 string   `protobuf:"bytes,6,opt,name=site,proto3" json:"site,omitempty"`
	SiteName             string   `protobuf:"bytes,7,opt,name=siteName,proto3" json:"siteName,omitempty"`
	ImageUrl             string   `protobuf:"bytes,8,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	VideoUrl             string   `protobuf:"bytes,9,opt,name=videoUrl,proto3" json:"videoUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMMLink) Reset()         { *m = CMMLink{} }
func (m *CMMLink) String() string { return proto.CompactTextString(m) }
func (*CMMLink) ProtoMessage()    {}
func (*CMMLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{1}
}

func (m *CMMLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMMLink.Unmarshal(m, b)
}
func (m *CMMLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMMLink.Marshal(b, m, deterministic)
}
func (m *CMMLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMMLink.Merge(m, src)
}
func (m *CMMLink) XXX_Size() int {
	return xxx_messageInfo_CMMLink.Size(m)
}
func (m *CMMLink) XXX_DiscardUnknown() {
	xxx_messageInfo_CMMLink.DiscardUnknown(m)
}

var xxx_messageInfo_CMMLink proto.InternalMessageInfo

func (m *CMMLink) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CMMLink) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CMMLink) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CMMLink) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CMMLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CMMLink) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *CMMLink) GetSiteName() string {
	if m != nil {
		return m.SiteName
	}
	return ""
}

func (m *CMMLink) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *CMMLink) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

type CMM struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	User                 *CMMUser `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Link                 *CMMLink `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Upvotes              int32    `protobuf:"varint,6,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Comments             int32    `protobuf:"varint,8,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMM) Reset()         { *m = CMM{} }
func (m *CMM) String() string { return proto.CompactTextString(m) }
func (*CMM) ProtoMessage()    {}
func (*CMM) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{2}
}

func (m *CMM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMM.Unmarshal(m, b)
}
func (m *CMM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMM.Marshal(b, m, deterministic)
}
func (m *CMM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMM.Merge(m, src)
}
func (m *CMM) XXX_Size() int {
	return xxx_messageInfo_CMM.Size(m)
}
func (m *CMM) XXX_DiscardUnknown() {
	xxx_messageInfo_CMM.DiscardUnknown(m)
}

var xxx_messageInfo_CMM proto.InternalMessageInfo

func (m *CMM) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CMM) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CMM) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CMM) GetUser() *CMMUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CMM) GetLink() *CMMLink {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *CMM) GetUpvotes() int32 {
	if m != nil {
		return m.Upvotes
	}
	return 0
}

func (m *CMM) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CMM) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

type CreateCMMRequest struct {
	Cmm                  *CMM     `protobuf:"bytes,1,opt,name=cmm,proto3" json:"cmm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCMMRequest) Reset()         { *m = CreateCMMRequest{} }
func (m *CreateCMMRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCMMRequest) ProtoMessage()    {}
func (*CreateCMMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{3}
}

func (m *CreateCMMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCMMRequest.Unmarshal(m, b)
}
func (m *CreateCMMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCMMRequest.Marshal(b, m, deterministic)
}
func (m *CreateCMMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCMMRequest.Merge(m, src)
}
func (m *CreateCMMRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCMMRequest.Size(m)
}
func (m *CreateCMMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCMMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCMMRequest proto.InternalMessageInfo

func (m *CreateCMMRequest) GetCmm() *CMM {
	if m != nil {
		return m.Cmm
	}
	return nil
}

type CreateCMMResponse struct {
	Cmm                  *CMM     `protobuf:"bytes,1,opt,name=cmm,proto3" json:"cmm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCMMResponse) Reset()         { *m = CreateCMMResponse{} }
func (m *CreateCMMResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCMMResponse) ProtoMessage()    {}
func (*CreateCMMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{4}
}

func (m *CreateCMMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCMMResponse.Unmarshal(m, b)
}
func (m *CreateCMMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCMMResponse.Marshal(b, m, deterministic)
}
func (m *CreateCMMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCMMResponse.Merge(m, src)
}
func (m *CreateCMMResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCMMResponse.Size(m)
}
func (m *CreateCMMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCMMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCMMResponse proto.InternalMessageInfo

func (m *CreateCMMResponse) GetCmm() *CMM {
	if m != nil {
		return m.Cmm
	}
	return nil
}

type UpdateCMMRequest struct {
	CmmId                int64    `protobuf:"varint,1,opt,name=cmmId,proto3" json:"cmmId,omitempty"`
	Cmm                  *CMM     `protobuf:"bytes,2,opt,name=cmm,proto3" json:"cmm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCMMRequest) Reset()         { *m = UpdateCMMRequest{} }
func (m *UpdateCMMRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCMMRequest) ProtoMessage()    {}
func (*UpdateCMMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{5}
}

func (m *UpdateCMMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCMMRequest.Unmarshal(m, b)
}
func (m *UpdateCMMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCMMRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCMMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCMMRequest.Merge(m, src)
}
func (m *UpdateCMMRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCMMRequest.Size(m)
}
func (m *UpdateCMMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCMMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCMMRequest proto.InternalMessageInfo

func (m *UpdateCMMRequest) GetCmmId() int64 {
	if m != nil {
		return m.CmmId
	}
	return 0
}

func (m *UpdateCMMRequest) GetCmm() *CMM {
	if m != nil {
		return m.Cmm
	}
	return nil
}

type UpdateCMMResponse struct {
	Cmm                  *CMM     `protobuf:"bytes,1,opt,name=cmm,proto3" json:"cmm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCMMResponse) Reset()         { *m = UpdateCMMResponse{} }
func (m *UpdateCMMResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCMMResponse) ProtoMessage()    {}
func (*UpdateCMMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{6}
}

func (m *UpdateCMMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCMMResponse.Unmarshal(m, b)
}
func (m *UpdateCMMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCMMResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCMMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCMMResponse.Merge(m, src)
}
func (m *UpdateCMMResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCMMResponse.Size(m)
}
func (m *UpdateCMMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCMMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCMMResponse proto.InternalMessageInfo

func (m *UpdateCMMResponse) GetCmm() *CMM {
	if m != nil {
		return m.Cmm
	}
	return nil
}

type DeleteCMMRequest struct {
	CmmId                int64    `protobuf:"varint,1,opt,name=cmmId,proto3" json:"cmmId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCMMRequest) Reset()         { *m = DeleteCMMRequest{} }
func (m *DeleteCMMRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCMMRequest) ProtoMessage()    {}
func (*DeleteCMMRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{7}
}

func (m *DeleteCMMRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCMMRequest.Unmarshal(m, b)
}
func (m *DeleteCMMRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCMMRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCMMRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCMMRequest.Merge(m, src)
}
func (m *DeleteCMMRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCMMRequest.Size(m)
}
func (m *DeleteCMMRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCMMRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCMMRequest proto.InternalMessageInfo

func (m *DeleteCMMRequest) GetCmmId() int64 {
	if m != nil {
		return m.CmmId
	}
	return 0
}

type DeleteCMMResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCMMResponse) Reset()         { *m = DeleteCMMResponse{} }
func (m *DeleteCMMResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCMMResponse) ProtoMessage()    {}
func (*DeleteCMMResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{8}
}

func (m *DeleteCMMResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCMMResponse.Unmarshal(m, b)
}
func (m *DeleteCMMResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCMMResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCMMResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCMMResponse.Merge(m, src)
}
func (m *DeleteCMMResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCMMResponse.Size(m)
}
func (m *DeleteCMMResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCMMResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCMMResponse proto.InternalMessageInfo

func (m *DeleteCMMResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type GetCMMByIDRequest struct {
	CmmId                int64    `protobuf:"varint,1,opt,name=cmmId,proto3" json:"cmmId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMByIDRequest) Reset()         { *m = GetCMMByIDRequest{} }
func (m *GetCMMByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMByIDRequest) ProtoMessage()    {}
func (*GetCMMByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{9}
}

func (m *GetCMMByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMByIDRequest.Unmarshal(m, b)
}
func (m *GetCMMByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMByIDRequest.Merge(m, src)
}
func (m *GetCMMByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMByIDRequest.Size(m)
}
func (m *GetCMMByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMByIDRequest proto.InternalMessageInfo

func (m *GetCMMByIDRequest) GetCmmId() int64 {
	if m != nil {
		return m.CmmId
	}
	return 0
}

type GetCMMByIDResponse struct {
	Cmm                  *CMM     `protobuf:"bytes,1,opt,name=cmm,proto3" json:"cmm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMByIDResponse) Reset()         { *m = GetCMMByIDResponse{} }
func (m *GetCMMByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMByIDResponse) ProtoMessage()    {}
func (*GetCMMByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{10}
}

func (m *GetCMMByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMByIDResponse.Unmarshal(m, b)
}
func (m *GetCMMByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMByIDResponse.Merge(m, src)
}
func (m *GetCMMByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMByIDResponse.Size(m)
}
func (m *GetCMMByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMByIDResponse proto.InternalMessageInfo

func (m *GetCMMByIDResponse) GetCmm() *CMM {
	if m != nil {
		return m.Cmm
	}
	return nil
}

type SearchCMMsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCMMsRequest) Reset()         { *m = SearchCMMsRequest{} }
func (m *SearchCMMsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchCMMsRequest) ProtoMessage()    {}
func (*SearchCMMsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{11}
}

func (m *SearchCMMsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCMMsRequest.Unmarshal(m, b)
}
func (m *SearchCMMsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCMMsRequest.Marshal(b, m, deterministic)
}
func (m *SearchCMMsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCMMsRequest.Merge(m, src)
}
func (m *SearchCMMsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchCMMsRequest.Size(m)
}
func (m *SearchCMMsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCMMsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCMMsRequest proto.InternalMessageInfo

func (m *SearchCMMsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchCMMsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchCMMsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchCMMsResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,4,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	Query                string   `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCMMsResponse) Reset()         { *m = SearchCMMsResponse{} }
func (m *SearchCMMsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchCMMsResponse) ProtoMessage()    {}
func (*SearchCMMsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{12}
}

func (m *SearchCMMsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCMMsResponse.Unmarshal(m, b)
}
func (m *SearchCMMsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCMMsResponse.Marshal(b, m, deterministic)
}
func (m *SearchCMMsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCMMsResponse.Merge(m, src)
}
func (m *SearchCMMsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchCMMsResponse.Size(m)
}
func (m *SearchCMMsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCMMsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCMMsResponse proto.InternalMessageInfo

func (m *SearchCMMsResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SearchCMMsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchCMMsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchCMMsResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *SearchCMMsResponse) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GetCMMOrderRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMOrderRequest) Reset()         { *m = GetCMMOrderRequest{} }
func (m *GetCMMOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMOrderRequest) ProtoMessage()    {}
func (*GetCMMOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{13}
}

func (m *GetCMMOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMOrderRequest.Unmarshal(m, b)
}
func (m *GetCMMOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMOrderRequest.Merge(m, src)
}
func (m *GetCMMOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMOrderRequest.Size(m)
}
func (m *GetCMMOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMOrderRequest proto.InternalMessageInfo

func (m *GetCMMOrderRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMOrderRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetCMMOrderResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMOrderResponse) Reset()         { *m = GetCMMOrderResponse{} }
func (m *GetCMMOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMOrderResponse) ProtoMessage()    {}
func (*GetCMMOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{14}
}

func (m *GetCMMOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMOrderResponse.Unmarshal(m, b)
}
func (m *GetCMMOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMOrderResponse.Merge(m, src)
}
func (m *GetCMMOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMOrderResponse.Size(m)
}
func (m *GetCMMOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMOrderResponse proto.InternalMessageInfo

func (m *GetCMMOrderResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetCMMOrderResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMOrderResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetCMMsByIDsRequest struct {
	Ids                  string   `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByIDsRequest) Reset()         { *m = GetCMMsByIDsRequest{} }
func (m *GetCMMsByIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByIDsRequest) ProtoMessage()    {}
func (*GetCMMsByIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{15}
}

func (m *GetCMMsByIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByIDsRequest.Unmarshal(m, b)
}
func (m *GetCMMsByIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByIDsRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMsByIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByIDsRequest.Merge(m, src)
}
func (m *GetCMMsByIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByIDsRequest.Size(m)
}
func (m *GetCMMsByIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByIDsRequest proto.InternalMessageInfo

func (m *GetCMMsByIDsRequest) GetIds() string {
	if m != nil {
		return m.Ids
	}
	return ""
}

type GetCMMsByIDsResponse struct {
	Data                 []*CMM   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByIDsResponse) Reset()         { *m = GetCMMsByIDsResponse{} }
func (m *GetCMMsByIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByIDsResponse) ProtoMessage()    {}
func (*GetCMMsByIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{16}
}

func (m *GetCMMsByIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByIDsResponse.Unmarshal(m, b)
}
func (m *GetCMMsByIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByIDsResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMsByIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByIDsResponse.Merge(m, src)
}
func (m *GetCMMsByIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByIDsResponse.Size(m)
}
func (m *GetCMMsByIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByIDsResponse proto.InternalMessageInfo

func (m *GetCMMsByIDsResponse) GetData() []*CMM {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCMMsRequest struct {
	Page                 int32               `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32               `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               GetCMMsRequest_Sort `protobuf:"varint,3,opt,name=sortBy,proto3,enum=discussproto.GetCMMsRequest_Sort" json:"sortBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetCMMsRequest) Reset()         { *m = GetCMMsRequest{} }
func (m *GetCMMsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMsRequest) ProtoMessage()    {}
func (*GetCMMsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{17}
}

func (m *GetCMMsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsRequest.Unmarshal(m, b)
}
func (m *GetCMMsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsRequest.Merge(m, src)
}
func (m *GetCMMsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMsRequest.Size(m)
}
func (m *GetCMMsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsRequest proto.InternalMessageInfo

func (m *GetCMMsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsRequest) GetSortBy() GetCMMsRequest_Sort {
	if m != nil {
		return m.SortBy
	}
	return GetCMMsRequest_new
}

type GetCMMsResponse struct {
	Data                 []*CMM   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsResponse) Reset()         { *m = GetCMMsResponse{} }
func (m *GetCMMsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMsResponse) ProtoMessage()    {}
func (*GetCMMsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{18}
}

func (m *GetCMMsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsResponse.Unmarshal(m, b)
}
func (m *GetCMMsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsResponse.Merge(m, src)
}
func (m *GetCMMsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMsResponse.Size(m)
}
func (m *GetCMMsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsResponse proto.InternalMessageInfo

func (m *GetCMMsResponse) GetData() []*CMM {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetCMMsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetCMMsResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

type GetCMMsByMeRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,4,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByMeRequest) Reset()         { *m = GetCMMsByMeRequest{} }
func (m *GetCMMsByMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByMeRequest) ProtoMessage()    {}
func (*GetCMMsByMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{19}
}

func (m *GetCMMsByMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByMeRequest.Unmarshal(m, b)
}
func (m *GetCMMsByMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByMeRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMsByMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByMeRequest.Merge(m, src)
}
func (m *GetCMMsByMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByMeRequest.Size(m)
}
func (m *GetCMMsByMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByMeRequest proto.InternalMessageInfo

func (m *GetCMMsByMeRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsByMeRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsByMeRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetCMMsByMeRequest) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetCMMsByMeResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByMeResponse) Reset()         { *m = GetCMMsByMeResponse{} }
func (m *GetCMMsByMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByMeResponse) ProtoMessage()    {}
func (*GetCMMsByMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{20}
}

func (m *GetCMMsByMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByMeResponse.Unmarshal(m, b)
}
func (m *GetCMMsByMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByMeResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMsByMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByMeResponse.Merge(m, src)
}
func (m *GetCMMsByMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByMeResponse.Size(m)
}
func (m *GetCMMsByMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByMeResponse proto.InternalMessageInfo

func (m *GetCMMsByMeResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetCMMsByMeResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsByMeResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsByMeResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetCMMsByMeResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetCMMsByMeResponse) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetCMMsByUserIDRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,4,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,5,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByUserIDRequest) Reset()         { *m = GetCMMsByUserIDRequest{} }
func (m *GetCMMsByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByUserIDRequest) ProtoMessage()    {}
func (*GetCMMsByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{21}
}

func (m *GetCMMsByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByUserIDRequest.Unmarshal(m, b)
}
func (m *GetCMMsByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByUserIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCMMsByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByUserIDRequest.Merge(m, src)
}
func (m *GetCMMsByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByUserIDRequest.Size(m)
}
func (m *GetCMMsByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByUserIDRequest proto.InternalMessageInfo

func (m *GetCMMsByUserIDRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetCMMsByUserIDRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsByUserIDRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsByUserIDRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetCMMsByUserIDRequest) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetCMMsByUserIDResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCMMsByUserIDResponse) Reset()         { *m = GetCMMsByUserIDResponse{} }
func (m *GetCMMsByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetCMMsByUserIDResponse) ProtoMessage()    {}
func (*GetCMMsByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6012c7cbe7c0078f, []int{22}
}

func (m *GetCMMsByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCMMsByUserIDResponse.Unmarshal(m, b)
}
func (m *GetCMMsByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCMMsByUserIDResponse.Marshal(b, m, deterministic)
}
func (m *GetCMMsByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCMMsByUserIDResponse.Merge(m, src)
}
func (m *GetCMMsByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetCMMsByUserIDResponse.Size(m)
}
func (m *GetCMMsByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCMMsByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCMMsByUserIDResponse proto.InternalMessageInfo

func (m *GetCMMsByUserIDResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetCMMsByUserIDResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCMMsByUserIDResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCMMsByUserIDResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetCMMsByUserIDResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetCMMsByUserIDResponse) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

func init() {
	proto.RegisterEnum("discussproto.GetCMMsRequest_Sort", GetCMMsRequest_Sort_name, GetCMMsRequest_Sort_value)
	proto.RegisterType((*CMMUser)(nil), "discussproto.CMMUser")
	proto.RegisterType((*CMMLink)(nil), "discussproto.CMMLink")
	proto.RegisterType((*CMM)(nil), "discussproto.CMM")
	proto.RegisterType((*CreateCMMRequest)(nil), "discussproto.CreateCMMRequest")
	proto.RegisterType((*CreateCMMResponse)(nil), "discussproto.CreateCMMResponse")
	proto.RegisterType((*UpdateCMMRequest)(nil), "discussproto.UpdateCMMRequest")
	proto.RegisterType((*UpdateCMMResponse)(nil), "discussproto.UpdateCMMResponse")
	proto.RegisterType((*DeleteCMMRequest)(nil), "discussproto.DeleteCMMRequest")
	proto.RegisterType((*DeleteCMMResponse)(nil), "discussproto.DeleteCMMResponse")
	proto.RegisterType((*GetCMMByIDRequest)(nil), "discussproto.GetCMMByIDRequest")
	proto.RegisterType((*GetCMMByIDResponse)(nil), "discussproto.GetCMMByIDResponse")
	proto.RegisterType((*SearchCMMsRequest)(nil), "discussproto.SearchCMMsRequest")
	proto.RegisterType((*SearchCMMsResponse)(nil), "discussproto.SearchCMMsResponse")
	proto.RegisterType((*GetCMMOrderRequest)(nil), "discussproto.GetCMMOrderRequest")
	proto.RegisterType((*GetCMMOrderResponse)(nil), "discussproto.GetCMMOrderResponse")
	proto.RegisterType((*GetCMMsByIDsRequest)(nil), "discussproto.GetCMMsByIDsRequest")
	proto.RegisterType((*GetCMMsByIDsResponse)(nil), "discussproto.GetCMMsByIDsResponse")
	proto.RegisterType((*GetCMMsRequest)(nil), "discussproto.GetCMMsRequest")
	proto.RegisterType((*GetCMMsResponse)(nil), "discussproto.GetCMMsResponse")
	proto.RegisterType((*GetCMMsByMeRequest)(nil), "discussproto.GetCMMsByMeRequest")
	proto.RegisterType((*GetCMMsByMeResponse)(nil), "discussproto.GetCMMsByMeResponse")
	proto.RegisterType((*GetCMMsByUserIDRequest)(nil), "discussproto.GetCMMsByUserIDRequest")
	proto.RegisterType((*GetCMMsByUserIDResponse)(nil), "discussproto.GetCMMsByUserIDResponse")
}

func init() { proto.RegisterFile("cmm.proto", fileDescriptor_6012c7cbe7c0078f) }

var fileDescriptor_6012c7cbe7c0078f = []byte{
	// 1104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0xcf, 0x6f, 0xe3, 0xc4,
	0x17, 0xc0, 0xd7, 0x71, 0x9c, 0x36, 0xaf, 0xfd, 0xb6, 0xc9, 0x6c, 0x37, 0x5f, 0xe3, 0x2d, 0x90,
	0x0e, 0xac, 0xb6, 0xbb, 0x62, 0x1b, 0xa9, 0x48, 0xc0, 0x22, 0x81, 0x44, 0x53, 0x09, 0x56, 0xc2,
	0x20, 0x5c, 0xf5, 0xc2, 0xcd, 0x6b, 0x0f, 0xd9, 0xa1, 0xb1, 0x9d, 0xf5, 0x4c, 0x5a, 0x45, 0x55,
	0xd1, 0x8a, 0x03, 0x67, 0x24, 0xae, 0xfc, 0x03, 0x1c, 0x90, 0xf8, 0x5f, 0xf8, 0x03, 0xb8, 0xf0,
	0x3f, 0x70, 0x45, 0xf3, 0xfc, 0x23, 0xb6, 0xe3, 0xb4, 0x44, 0xf4, 0xc0, 0x29, 0xf3, 0xe6, 0xbd,
	0x99, 0xcf, 0x7b, 0x6f, 0xde, 0xcc, 0x73, 0xa0, 0xed, 0x05, 0xc1, 0xc1, 0x24, 0x8e, 0x64, 0x44,
	0x36, 0x7d, 0x2e, 0xbc, 0xa9, 0x10, 0x28, 0x59, 0xbb, 0xa3, 0x28, 0x1a, 0x8d, 0xd9, 0xc0, 0x9d,
	0xf0, 0x81, 0x1b, 0x86, 0x91, 0x74, 0x25, 0x8f, 0x42, 0x91, 0xd8, 0x5a, 0xef, 0x8d, 0xb8, 0x7c,
	0x31, 0x7d, 0x7e, 0xe0, 0x45, 0xc1, 0x20, 0xb8, 0xe0, 0xf2, 0x2c, 0xba, 0x18, 0x8c, 0xa2, 0x27,
	0xa8, 0x7c, 0x72, 0xee, 0x8e, 0xb9, 0xef, 0xca, 0x28, 0x16, 0x83, 0x7c, 0x98, 0xac, 0xa3, 0x02,
	0xd6, 0x86, 0xb6, 0x7d, 0x2a, 0x58, 0x4c, 0xb6, 0xa0, 0xc1, 0x7d, 0x53, 0xeb, 0x6b, 0xfb, 0xba,
	0xd3, 0xe0, 0x3e, 0x79, 0x07, 0xba, 0xf2, 0x82, 0x4b, 0xc9, 0xe2, 0x13, 0x2f, 0x66, 0x2c, 0xfc,
	0xc2, 0x0d, 0x98, 0xd9, 0xe8, 0x6b, 0xfb, 0x6d, 0x67, 0x51, 0x41, 0x08, 0x34, 0x43, 0x65, 0xa0,
	0xa3, 0x01, 0x8e, 0x49, 0x0f, 0x5a, 0xee, 0xb9, 0x2b, 0xdd, 0xd8, 0x6c, 0xe2, 0x6c, 0x2a, 0xd1,
	0x3f, 0x34, 0xa4, 0x7e, 0xce, 0xc3, 0xb3, 0x05, 0xea, 0x0e, 0x18, 0x92, 0xcb, 0x71, 0x46, 0x4a,
	0x04, 0xd2, 0x87, 0x0d, 0x9f, 0x09, 0x2f, 0xe6, 0x13, 0x15, 0x74, 0x0a, 0x29, 0x4e, 0x29, 0xbe,
	0x9c, 0x4d, 0x58, 0x4a, 0xc2, 0x31, 0xe9, 0x80, 0x3e, 0x8d, 0xc7, 0xa6, 0x81, 0x53, 0x6a, 0xa8,
	0xac, 0x04, 0x97, 0xcc, 0x6c, 0x25, 0x56, 0x6a, 0x4c, 0x2c, 0x58, 0x57, 0xbf, 0x18, 0xde, 0x1a,
	0xce, 0xe7, 0xb2, 0xd2, 0xf1, 0xc0, 0x1d, 0xb1, 0xd3, 0x78, 0x6c, 0xae, 0x27, 0xba, 0x4c, 0x56,
	0xba, 0x73, 0xee, 0xb3, 0x48, 0xe9, 0xda, 0x89, 0x2e, 0x93, 0xe9, 0x5f, 0x1a, 0xe8, 0x43, 0xdb,
	0xbe, 0xb5, 0xe8, 0x1e, 0x41, 0x73, 0x2a, 0x58, 0x92, 0xc7, 0x8d, 0xc3, 0x7b, 0x07, 0xc5, 0xca,
	0x38, 0x48, 0x0f, 0xd0, 0x41, 0x13, 0x65, 0x3a, 0xe6, 0xe1, 0x19, 0x46, 0x5d, 0x67, 0xaa, 0xb2,
	0xee, 0xa0, 0x09, 0x31, 0x61, 0x6d, 0x3a, 0x39, 0x8f, 0x24, 0x13, 0x98, 0x10, 0xc3, 0xc9, 0x44,
	0xb2, 0x0b, 0x6d, 0x2f, 0x66, 0xae, 0x64, 0xfe, 0x27, 0x32, 0x4d, 0xca, 0x7c, 0x42, 0x45, 0xee,
	0x45, 0x41, 0xc0, 0x42, 0x29, 0x30, 0x2b, 0x86, 0x93, 0xcb, 0xf4, 0x7d, 0xe8, 0x0c, 0xd1, 0x70,
	0x68, 0xdb, 0x0e, 0x7b, 0x39, 0x65, 0x42, 0x92, 0xb7, 0x40, 0xf7, 0x82, 0x00, 0xd3, 0xb0, 0x71,
	0xd8, 0x5d, 0xf0, 0xc8, 0x51, 0x5a, 0xfa, 0x01, 0x74, 0x0b, 0x0b, 0xc5, 0x24, 0x0a, 0x05, 0xfb,
	0x67, 0x2b, 0x6d, 0xe8, 0x9c, 0x4e, 0xfc, 0x32, 0x72, 0x07, 0x0c, 0x2f, 0x08, 0x9e, 0x65, 0xb9,
	0x4f, 0x84, 0x6c, 0xbb, 0xc6, 0x4d, 0x8e, 0x14, 0xb6, 0x5b, 0xc5, 0x91, 0x7d, 0xe8, 0x1c, 0xb3,
	0x31, 0xbb, 0xd9, 0x11, 0xfa, 0x10, 0xba, 0x05, 0xcb, 0x94, 0x41, 0xa0, 0xe9, 0x47, 0x21, 0x43,
	0xcb, 0x75, 0x07, 0xc7, 0xf4, 0x11, 0x74, 0x3f, 0x65, 0x72, 0x68, 0xdb, 0x47, 0xb3, 0x67, 0xc7,
	0xd7, 0xef, 0xf9, 0x14, 0x48, 0xd1, 0x74, 0x15, 0xc7, 0x4f, 0xa0, 0x7b, 0xc2, 0xdc, 0xd8, 0x7b,
	0x31, 0xb4, 0x6d, 0x91, 0x51, 0x08, 0x34, 0x27, 0xee, 0x28, 0x71, 0xc7, 0x70, 0x70, 0xac, 0xc8,
	0x63, 0x1e, 0x70, 0x89, 0x29, 0x34, 0x9c, 0x44, 0x50, 0xb3, 0x2f, 0xa7, 0x2c, 0x9e, 0xa5, 0x95,
	0x9b, 0x08, 0xf4, 0x3b, 0x20, 0xc5, 0x4d, 0x53, 0x7f, 0x3a, 0xa0, 0x73, 0x5f, 0x98, 0x5a, 0x5f,
	0xdf, 0xd7, 0x1d, 0x35, 0xcc, 0x39, 0x8d, 0x3a, 0x8e, 0x5e, 0xe4, 0xf4, 0xa0, 0x25, 0xa2, 0x58,
	0x1e, 0xcd, 0xb2, 0xf7, 0x24, 0x91, 0xe6, 0x7c, 0xa3, 0xc8, 0xff, 0x38, 0xcb, 0xc7, 0x97, 0xb1,
	0xcf, 0xe2, 0x95, 0xa3, 0xa2, 0x5f, 0xc1, 0xdd, 0xd2, 0xfa, 0x7f, 0x1f, 0x00, 0x7d, 0x98, 0x6d,
	0x29, 0xd4, 0x19, 0xe5, 0x99, 0xce, 0xb7, 0xc4, 0x77, 0x8a, 0xfb, 0x82, 0x7e, 0x04, 0x3b, 0x65,
	0xc3, 0x14, 0xfe, 0x00, 0x9a, 0xbe, 0x2b, 0x5d, 0xa4, 0xd7, 0x1e, 0x27, 0xaa, 0xe9, 0x0f, 0x1a,
	0x6c, 0xa5, 0xeb, 0x57, 0x3f, 0xcd, 0xa7, 0x79, 0x96, 0x95, 0xef, 0x5b, 0x87, 0x7b, 0x65, 0x4a,
	0x79, 0xdf, 0x83, 0x93, 0x28, 0x96, 0xd9, 0x41, 0xd0, 0x6d, 0x68, 0x2a, 0x99, 0xac, 0x81, 0x1e,
	0xb2, 0x8b, 0xce, 0x1d, 0xfa, 0xa3, 0x06, 0xdb, 0xf9, 0x82, 0x95, 0x62, 0x58, 0xa1, 0x2c, 0xd4,
	0x75, 0x88, 0xa6, 0xa1, 0xc4, 0xaa, 0x30, 0x9c, 0x44, 0x28, 0x14, 0x8b, 0x51, 0x2c, 0x16, 0xfa,
	0x4a, 0xcb, 0xea, 0x42, 0x1c, 0xcd, 0x6c, 0xb6, 0x7a, 0x7e, 0x7a, 0xa5, 0xfc, 0xcc, 0xab, 0x70,
	0x1f, 0xb6, 0x93, 0xd1, 0x31, 0x8f, 0x99, 0x87, 0x2f, 0x79, 0x52, 0xa6, 0xd5, 0x69, 0xfa, 0x8b,
	0x56, 0xa8, 0x03, 0xe5, 0xc2, 0x2d, 0xdc, 0x8d, 0x95, 0x92, 0x50, 0xe7, 0x6b, 0xab, 0xde, 0xd7,
	0x9f, 0x35, 0xe8, 0xe5, 0xbe, 0xaa, 0x36, 0x33, 0x7f, 0x86, 0x7a, 0xd0, 0x52, 0x1d, 0x27, 0x7f,
	0x87, 0x52, 0xe9, 0x16, 0x2e, 0x74, 0x8d, 0x7b, 0x46, 0xbd, 0x7b, 0xbf, 0x6a, 0xf0, 0xff, 0x05,
	0xf7, 0xfe, 0xbb, 0xe9, 0x3c, 0xfc, 0x6d, 0x1d, 0x60, 0x68, 0xdb, 0x27, 0x2c, 0x3e, 0xe7, 0x1e,
	0x23, 0x2e, 0xb4, 0xf3, 0xa6, 0x47, 0xde, 0xa8, 0x5c, 0x85, 0x4a, 0x1b, 0xb5, 0xde, 0x5c, 0xaa,
	0x4f, 0x02, 0xa6, 0x77, 0xbf, 0xff, 0xfd, 0xcf, 0x9f, 0x1a, 0xff, 0xa3, 0xeb, 0xf8, 0x91, 0xe8,
	0x05, 0xc1, 0x87, 0xda, 0x63, 0xc2, 0xa1, 0x9d, 0xb7, 0xb3, 0x2a, 0xa2, 0xda, 0x36, 0xab, 0x88,
	0x85, 0x3e, 0x48, 0xef, 0x23, 0xe2, 0xde, 0x61, 0x27, 0x43, 0x0c, 0x2e, 0xb1, 0xfb, 0x5c, 0x29,
	0xd4, 0x37, 0xd0, 0xce, 0xbb, 0x5a, 0x15, 0x55, 0x6d, 0x8c, 0x55, 0xd4, 0x42, 0x3b, 0xa4, 0x26,
	0xa2, 0xc8, 0xe3, 0x05, 0x14, 0x19, 0xc1, 0x46, 0xe1, 0xfa, 0x90, 0x7e, 0xed, 0x03, 0x55, 0xb8,
	0xdc, 0xd6, 0xde, 0x35, 0x16, 0xe5, 0xdc, 0x91, 0x8d, 0x9c, 0x16, 0x30, 0x12, 0x03, 0xcc, 0x5b,
	0x18, 0xa9, 0x78, 0xbc, 0xd0, 0x31, 0xad, 0xfe, 0x72, 0x83, 0x94, 0xb2, 0x87, 0x94, 0xfb, 0xe4,
	0x35, 0xa4, 0x4c, 0x90, 0x23, 0xd0, 0x6c, 0x70, 0x89, 0x5d, 0xeb, 0x8a, 0x7c, 0x9b, 0x05, 0x87,
	0x6d, 0xa7, 0x3e, 0xb8, 0x62, 0x47, 0xab, 0x0f, 0xae, 0xd4, 0xb3, 0x68, 0x0f, 0xb1, 0x1d, 0xb2,
	0x55, 0xc0, 0xaa, 0xfb, 0xc0, 0x61, 0xb3, 0xd8, 0x66, 0xc8, 0xb2, 0x3c, 0xcd, 0x7b, 0x95, 0x45,
	0xaf, 0x33, 0x49, 0x71, 0x04, 0x71, 0x9b, 0x04, 0xe6, 0x38, 0x72, 0x06, 0x30, 0xff, 0x3a, 0xa9,
	0xa6, 0x72, 0xe1, 0x13, 0xc7, 0xea, 0x2f, 0x37, 0x48, 0x21, 0x16, 0x42, 0x76, 0x08, 0x29, 0xc4,
	0x94, 0x15, 0xc8, 0x67, 0xb0, 0x96, 0x3a, 0x46, 0x76, 0xaf, 0xeb, 0x5e, 0xd6, 0xeb, 0x4b, 0xb4,
	0x29, 0xe3, 0x0e, 0x79, 0x35, 0x6f, 0x60, 0xd9, 0xfb, 0x42, 0xde, 0x5e, 0x92, 0x82, 0xd2, 0xeb,
	0x68, 0x3d, 0xb8, 0xc1, 0x2a, 0x45, 0xf4, 0x31, 0x0c, 0x8b, 0x98, 0x69, 0x18, 0xea, 0x0d, 0x1d,
	0x5c, 0x26, 0x2f, 0xe9, 0x95, 0x0a, 0xea, 0x68, 0xeb, 0xeb, 0xd2, 0x1f, 0xc1, 0xe7, 0x2d, 0xfc,
	0x79, 0xf7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x9c, 0x0f, 0xf9, 0x2a, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CMMServiceClient is the client API for CMMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CMMServiceClient interface {
	CreateCMM(ctx context.Context, in *CreateCMMRequest, opts ...grpc.CallOption) (*CreateCMMResponse, error)
	UpdateCMM(ctx context.Context, in *UpdateCMMRequest, opts ...grpc.CallOption) (*UpdateCMMResponse, error)
	DeleteCMM(ctx context.Context, in *DeleteCMMRequest, opts ...grpc.CallOption) (*DeleteCMMResponse, error)
	GetCMMsByMe(ctx context.Context, in *GetCMMsByMeRequest, opts ...grpc.CallOption) (*GetCMMsByMeResponse, error)
	SearchCMMs(ctx context.Context, in *SearchCMMsRequest, opts ...grpc.CallOption) (*SearchCMMsResponse, error)
	GetCMMOrder(ctx context.Context, in *GetCMMOrderRequest, opts ...grpc.CallOption) (*GetCMMOrderResponse, error)
	GetCMMsByIDs(ctx context.Context, in *GetCMMsByIDsRequest, opts ...grpc.CallOption) (*GetCMMsByIDsResponse, error)
	GetCMMByID(ctx context.Context, in *GetCMMByIDRequest, opts ...grpc.CallOption) (*GetCMMByIDResponse, error)
	GetCMMs(ctx context.Context, in *GetCMMsRequest, opts ...grpc.CallOption) (*GetCMMsResponse, error)
	GetCMMsByUserID(ctx context.Context, in *GetCMMsByUserIDRequest, opts ...grpc.CallOption) (*GetCMMsByUserIDResponse, error)
}

type cMMServiceClient struct {
	cc *grpc.ClientConn
}

func NewCMMServiceClient(cc *grpc.ClientConn) CMMServiceClient {
	return &cMMServiceClient{cc}
}

func (c *cMMServiceClient) CreateCMM(ctx context.Context, in *CreateCMMRequest, opts ...grpc.CallOption) (*CreateCMMResponse, error) {
	out := new(CreateCMMResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/CreateCMM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) UpdateCMM(ctx context.Context, in *UpdateCMMRequest, opts ...grpc.CallOption) (*UpdateCMMResponse, error) {
	out := new(UpdateCMMResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/UpdateCMM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) DeleteCMM(ctx context.Context, in *DeleteCMMRequest, opts ...grpc.CallOption) (*DeleteCMMResponse, error) {
	out := new(DeleteCMMResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/DeleteCMM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMsByMe(ctx context.Context, in *GetCMMsByMeRequest, opts ...grpc.CallOption) (*GetCMMsByMeResponse, error) {
	out := new(GetCMMsByMeResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMsByMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) SearchCMMs(ctx context.Context, in *SearchCMMsRequest, opts ...grpc.CallOption) (*SearchCMMsResponse, error) {
	out := new(SearchCMMsResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/SearchCMMs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMOrder(ctx context.Context, in *GetCMMOrderRequest, opts ...grpc.CallOption) (*GetCMMOrderResponse, error) {
	out := new(GetCMMOrderResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMsByIDs(ctx context.Context, in *GetCMMsByIDsRequest, opts ...grpc.CallOption) (*GetCMMsByIDsResponse, error) {
	out := new(GetCMMsByIDsResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMsByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMByID(ctx context.Context, in *GetCMMByIDRequest, opts ...grpc.CallOption) (*GetCMMByIDResponse, error) {
	out := new(GetCMMByIDResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMs(ctx context.Context, in *GetCMMsRequest, opts ...grpc.CallOption) (*GetCMMsResponse, error) {
	out := new(GetCMMsResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cMMServiceClient) GetCMMsByUserID(ctx context.Context, in *GetCMMsByUserIDRequest, opts ...grpc.CallOption) (*GetCMMsByUserIDResponse, error) {
	out := new(GetCMMsByUserIDResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CMMService/GetCMMsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMMServiceServer is the server API for CMMService service.
type CMMServiceServer interface {
	CreateCMM(context.Context, *CreateCMMRequest) (*CreateCMMResponse, error)
	UpdateCMM(context.Context, *UpdateCMMRequest) (*UpdateCMMResponse, error)
	DeleteCMM(context.Context, *DeleteCMMRequest) (*DeleteCMMResponse, error)
	GetCMMsByMe(context.Context, *GetCMMsByMeRequest) (*GetCMMsByMeResponse, error)
	SearchCMMs(context.Context, *SearchCMMsRequest) (*SearchCMMsResponse, error)
	GetCMMOrder(context.Context, *GetCMMOrderRequest) (*GetCMMOrderResponse, error)
	GetCMMsByIDs(context.Context, *GetCMMsByIDsRequest) (*GetCMMsByIDsResponse, error)
	GetCMMByID(context.Context, *GetCMMByIDRequest) (*GetCMMByIDResponse, error)
	GetCMMs(context.Context, *GetCMMsRequest) (*GetCMMsResponse, error)
	GetCMMsByUserID(context.Context, *GetCMMsByUserIDRequest) (*GetCMMsByUserIDResponse, error)
}

// UnimplementedCMMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCMMServiceServer struct {
}

func (*UnimplementedCMMServiceServer) CreateCMM(ctx context.Context, req *CreateCMMRequest) (*CreateCMMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCMM not implemented")
}
func (*UnimplementedCMMServiceServer) UpdateCMM(ctx context.Context, req *UpdateCMMRequest) (*UpdateCMMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCMM not implemented")
}
func (*UnimplementedCMMServiceServer) DeleteCMM(ctx context.Context, req *DeleteCMMRequest) (*DeleteCMMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCMM not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMsByMe(ctx context.Context, req *GetCMMsByMeRequest) (*GetCMMsByMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMsByMe not implemented")
}
func (*UnimplementedCMMServiceServer) SearchCMMs(ctx context.Context, req *SearchCMMsRequest) (*SearchCMMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCMMs not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMOrder(ctx context.Context, req *GetCMMOrderRequest) (*GetCMMOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMOrder not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMsByIDs(ctx context.Context, req *GetCMMsByIDsRequest) (*GetCMMsByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMsByIDs not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMByID(ctx context.Context, req *GetCMMByIDRequest) (*GetCMMByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMByID not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMs(ctx context.Context, req *GetCMMsRequest) (*GetCMMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMs not implemented")
}
func (*UnimplementedCMMServiceServer) GetCMMsByUserID(ctx context.Context, req *GetCMMsByUserIDRequest) (*GetCMMsByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCMMsByUserID not implemented")
}

func RegisterCMMServiceServer(s *grpc.Server, srv CMMServiceServer) {
	s.RegisterService(&_CMMService_serviceDesc, srv)
}

func _CMMService_CreateCMM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCMMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).CreateCMM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/CreateCMM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).CreateCMM(ctx, req.(*CreateCMMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_UpdateCMM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCMMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).UpdateCMM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/UpdateCMM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).UpdateCMM(ctx, req.(*UpdateCMMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_DeleteCMM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCMMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).DeleteCMM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/DeleteCMM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).DeleteCMM(ctx, req.(*DeleteCMMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMsByMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMsByMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMsByMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMsByMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMsByMe(ctx, req.(*GetCMMsByMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_SearchCMMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCMMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).SearchCMMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/SearchCMMs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).SearchCMMs(ctx, req.(*SearchCMMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMOrder(ctx, req.(*GetCMMOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMsByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMsByIDs(ctx, req.(*GetCMMsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMByID(ctx, req.(*GetCMMByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMs(ctx, req.(*GetCMMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CMMService_GetCMMsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCMMsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMMServiceServer).GetCMMsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CMMService/GetCMMsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMMServiceServer).GetCMMsByUserID(ctx, req.(*GetCMMsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CMMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discussproto.CMMService",
	HandlerType: (*CMMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCMM",
			Handler:    _CMMService_CreateCMM_Handler,
		},
		{
			MethodName: "UpdateCMM",
			Handler:    _CMMService_UpdateCMM_Handler,
		},
		{
			MethodName: "DeleteCMM",
			Handler:    _CMMService_DeleteCMM_Handler,
		},
		{
			MethodName: "GetCMMsByMe",
			Handler:    _CMMService_GetCMMsByMe_Handler,
		},
		{
			MethodName: "SearchCMMs",
			Handler:    _CMMService_SearchCMMs_Handler,
		},
		{
			MethodName: "GetCMMOrder",
			Handler:    _CMMService_GetCMMOrder_Handler,
		},
		{
			MethodName: "GetCMMsByIDs",
			Handler:    _CMMService_GetCMMsByIDs_Handler,
		},
		{
			MethodName: "GetCMMByID",
			Handler:    _CMMService_GetCMMByID_Handler,
		},
		{
			MethodName: "GetCMMs",
			Handler:    _CMMService_GetCMMs_Handler,
		},
		{
			MethodName: "GetCMMsByUserID",
			Handler:    _CMMService_GetCMMsByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmm.proto",
}
