// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.proto

package discussproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommentUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	TwitterScreenName    string   `protobuf:"bytes,4,opt,name=twitterScreenName,proto3" json:"twitterScreenName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentUser) Reset()         { *m = CommentUser{} }
func (m *CommentUser) String() string { return proto.CompactTextString(m) }
func (*CommentUser) ProtoMessage()    {}
func (*CommentUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{0}
}

func (m *CommentUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentUser.Unmarshal(m, b)
}
func (m *CommentUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentUser.Marshal(b, m, deterministic)
}
func (m *CommentUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentUser.Merge(m, src)
}
func (m *CommentUser) XXX_Size() int {
	return xxx_messageInfo_CommentUser.Size(m)
}
func (m *CommentUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentUser.DiscardUnknown(m)
}

var xxx_messageInfo_CommentUser proto.InternalMessageInfo

func (m *CommentUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommentUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommentUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CommentUser) GetTwitterScreenName() string {
	if m != nil {
		return m.TwitterScreenName
	}
	return ""
}

type CommentMeta struct {
	User                 *CommentUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommentMeta) Reset()         { *m = CommentMeta{} }
func (m *CommentMeta) String() string { return proto.CompactTextString(m) }
func (*CommentMeta) ProtoMessage()    {}
func (*CommentMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{1}
}

func (m *CommentMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentMeta.Unmarshal(m, b)
}
func (m *CommentMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentMeta.Marshal(b, m, deterministic)
}
func (m *CommentMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentMeta.Merge(m, src)
}
func (m *CommentMeta) XXX_Size() int {
	return xxx_messageInfo_CommentMeta.Size(m)
}
func (m *CommentMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CommentMeta proto.InternalMessageInfo

func (m *CommentMeta) GetUser() *CommentUser {
	if m != nil {
		return m.User
	}
	return nil
}

type Comment struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ObjectId             string            `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Content              string            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt            string            `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId               int64             `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Viewed               bool              `protobuf:"varint,6,opt,name=viewed,proto3" json:"viewed,omitempty"`
	Upvotes              int32             `protobuf:"varint,7,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	Meta                 *CommentMeta      `protobuf:"bytes,8,opt,name=meta,proto3" json:"meta,omitempty"`
	Voted                CommentUpvoteType `protobuf:"varint,9,opt,name=voted,proto3,enum=discussproto.CommentUpvoteType" json:"voted,omitempty"`
	ConversationId       int64             `protobuf:"varint,10,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{2}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Comment) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Comment) GetViewed() bool {
	if m != nil {
		return m.Viewed
	}
	return false
}

func (m *Comment) GetUpvotes() int32 {
	if m != nil {
		return m.Upvotes
	}
	return 0
}

func (m *Comment) GetMeta() *CommentMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Comment) GetVoted() CommentUpvoteType {
	if m != nil {
		return m.Voted
	}
	return CommentUpvoteType_NONE
}

func (m *Comment) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type GetCommentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentRequest) Reset()         { *m = GetCommentRequest{} }
func (m *GetCommentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentRequest) ProtoMessage()    {}
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{3}
}

func (m *GetCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentRequest.Unmarshal(m, b)
}
func (m *GetCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentRequest.Merge(m, src)
}
func (m *GetCommentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentRequest.Size(m)
}
func (m *GetCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentRequest proto.InternalMessageInfo

func (m *GetCommentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetCommentResponse struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentResponse) Reset()         { *m = GetCommentResponse{} }
func (m *GetCommentResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentResponse) ProtoMessage()    {}
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{4}
}

func (m *GetCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentResponse.Unmarshal(m, b)
}
func (m *GetCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentResponse.Marshal(b, m, deterministic)
}
func (m *GetCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentResponse.Merge(m, src)
}
func (m *GetCommentResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentResponse.Size(m)
}
func (m *GetCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentResponse proto.InternalMessageInfo

func (m *GetCommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type GetCommentsRequest struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	IncludesFields       string   `protobuf:"bytes,6,opt,name=includesFields,proto3" json:"includesFields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentsRequest) Reset()         { *m = GetCommentsRequest{} }
func (m *GetCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentsRequest) ProtoMessage()    {}
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{5}
}

func (m *GetCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentsRequest.Unmarshal(m, b)
}
func (m *GetCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentsRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentsRequest.Merge(m, src)
}
func (m *GetCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentsRequest.Size(m)
}
func (m *GetCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentsRequest proto.InternalMessageInfo

func (m *GetCommentsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetCommentsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetCommentsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCommentsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCommentsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetCommentsRequest) GetIncludesFields() string {
	if m != nil {
		return m.IncludesFields
	}
	return ""
}

type GetCommentsResponse struct {
	Data                 []*Comment `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Count                int32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Limit                int32      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32      `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	SortBy               string     `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCommentsResponse) Reset()         { *m = GetCommentsResponse{} }
func (m *GetCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCommentsResponse) ProtoMessage()    {}
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{6}
}

func (m *GetCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentsResponse.Unmarshal(m, b)
}
func (m *GetCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentsResponse.Marshal(b, m, deterministic)
}
func (m *GetCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentsResponse.Merge(m, src)
}
func (m *GetCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCommentsResponse.Size(m)
}
func (m *GetCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentsResponse proto.InternalMessageInfo

func (m *GetCommentsResponse) GetData() []*Comment {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetCommentsResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetCommentsResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCommentsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCommentsResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

type CommentNotification struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentNotification) Reset()         { *m = CommentNotification{} }
func (m *CommentNotification) String() string { return proto.CompactTextString(m) }
func (*CommentNotification) ProtoMessage()    {}
func (*CommentNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{7}
}

func (m *CommentNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentNotification.Unmarshal(m, b)
}
func (m *CommentNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentNotification.Marshal(b, m, deterministic)
}
func (m *CommentNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentNotification.Merge(m, src)
}
func (m *CommentNotification) XXX_Size() int {
	return xxx_messageInfo_CommentNotification.Size(m)
}
func (m *CommentNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentNotification.DiscardUnknown(m)
}

var xxx_messageInfo_CommentNotification proto.InternalMessageInfo

func (m *CommentNotification) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *CommentNotification) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateCommentRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string               `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Comment              *Comment             `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Notification         *CommentNotification `protobuf:"bytes,4,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{8}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateCommentRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *CreateCommentRequest) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *CreateCommentRequest) GetNotification() *CommentNotification {
	if m != nil {
		return m.Notification
	}
	return nil
}

type CreateCommentResponse struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{9}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

func (m *CreateCommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func init() {
	proto.RegisterType((*CommentUser)(nil), "discussproto.CommentUser")
	proto.RegisterType((*CommentMeta)(nil), "discussproto.CommentMeta")
	proto.RegisterType((*Comment)(nil), "discussproto.Comment")
	proto.RegisterType((*GetCommentRequest)(nil), "discussproto.GetCommentRequest")
	proto.RegisterType((*GetCommentResponse)(nil), "discussproto.GetCommentResponse")
	proto.RegisterType((*GetCommentsRequest)(nil), "discussproto.GetCommentsRequest")
	proto.RegisterType((*GetCommentsResponse)(nil), "discussproto.GetCommentsResponse")
	proto.RegisterType((*CommentNotification)(nil), "discussproto.CommentNotification")
	proto.RegisterType((*CreateCommentRequest)(nil), "discussproto.CreateCommentRequest")
	proto.RegisterType((*CreateCommentResponse)(nil), "discussproto.CreateCommentResponse")
}

func init() { proto.RegisterFile("comment.proto", fileDescriptor_749aee09ea917828) }

var fileDescriptor_749aee09ea917828 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0xed, 0x24, 0x6d, 0xb2, 0x69, 0x23, 0x75, 0xdb, 0xfe, 0x32, 0x51, 0xa5, 0xba, 0xae,
	0xa8, 0x02, 0xb4, 0xb1, 0x14, 0x04, 0x07, 0xc4, 0x85, 0x56, 0x05, 0x7a, 0xa0, 0x12, 0x5b, 0xb8,
	0x70, 0xdb, 0xda, 0x43, 0x58, 0x48, 0xbc, 0xc6, 0xbb, 0x4e, 0x54, 0x55, 0x15, 0x12, 0x07, 0x5e,
	0x80, 0x0b, 0xcf, 0xc0, 0x23, 0x70, 0xe7, 0x09, 0x78, 0x05, 0xae, 0xbc, 0x03, 0xf2, 0x78, 0x93,
	0x3a, 0x69, 0x1a, 0x21, 0x38, 0xc5, 0xdf, 0x78, 0x66, 0xbe, 0x6f, 0x66, 0xbe, 0x24, 0x64, 0x39,
	0x90, 0xfd, 0x3e, 0x44, 0xba, 0x1d, 0x27, 0x52, 0x4b, 0xba, 0x14, 0x0a, 0x15, 0xa4, 0x4a, 0x21,
	0x6a, 0x6e, 0x74, 0xa5, 0xec, 0xf6, 0xc0, 0xe7, 0xb1, 0xf0, 0x79, 0x14, 0x49, 0xcd, 0xb5, 0x90,
	0x91, 0xca, 0x73, 0x9b, 0xf7, 0xbb, 0x42, 0xbf, 0x49, 0x4f, 0xdb, 0x81, 0xec, 0xfb, 0xfd, 0xa1,
	0xd0, 0xef, 0xe4, 0xd0, 0xef, 0xca, 0x3d, 0x7c, 0xb9, 0x37, 0xe0, 0x3d, 0x11, 0x72, 0x2d, 0x13,
	0xe5, 0x8f, 0x1f, 0x4d, 0xdd, 0xaa, 0xa1, 0x7c, 0x19, 0x0f, 0xa4, 0x86, 0x3c, 0xe8, 0x0d, 0x49,
	0xfd, 0xc0, 0x84, 0x15, 0x24, 0xb4, 0x41, 0x6c, 0x11, 0x3a, 0x96, 0x6b, 0xb5, 0x4a, 0xcc, 0x16,
	0x21, 0xa5, 0xa4, 0x1c, 0xf1, 0x3e, 0x38, 0xb6, 0x6b, 0xb5, 0x6a, 0x0c, 0x9f, 0xe9, 0xff, 0x64,
	0x81, 0x0f, 0xb8, 0xe6, 0x89, 0x53, 0xc2, 0xa8, 0x41, 0x74, 0x97, 0xac, 0xe8, 0xa1, 0xd0, 0x1a,
	0x92, 0x93, 0x20, 0x01, 0x88, 0x8e, 0xb3, 0xc2, 0x32, 0xa6, 0x5c, 0x7d, 0xe1, 0x3d, 0x1c, 0x13,
	0x3f, 0x03, 0xcd, 0xe9, 0x1e, 0x29, 0xa7, 0x0a, 0x12, 0xa4, 0xae, 0x77, 0x6e, 0xb4, 0x8b, 0xfb,
	0x68, 0x17, 0x14, 0x32, 0x4c, 0xf3, 0xbe, 0xdb, 0x64, 0xd1, 0x44, 0x0b, 0x9a, 0x6b, 0xa8, 0xb9,
	0x49, 0xaa, 0xf2, 0xf4, 0x2d, 0x04, 0xfa, 0x28, 0x34, 0xba, 0xc7, 0x98, 0x3a, 0x64, 0x31, 0x90,
	0x91, 0x86, 0x48, 0x1b, 0xf1, 0x23, 0x48, 0x37, 0x48, 0x2d, 0x48, 0x80, 0x6b, 0x08, 0x1f, 0x69,
	0xa3, 0xfa, 0x32, 0x90, 0xcd, 0x9c, 0xf1, 0x1e, 0x85, 0x4e, 0x05, 0x77, 0x63, 0x50, 0x16, 0x1f,
	0x08, 0x18, 0x42, 0xe8, 0x2c, 0xb8, 0x56, 0xab, 0xca, 0x0c, 0xca, 0x78, 0x52, 0x5c, 0xb3, 0x72,
	0x16, 0x5d, 0xab, 0x55, 0x61, 0x23, 0x98, 0x0d, 0xda, 0x07, 0xcd, 0x9d, 0xea, 0x9c, 0x41, 0xb3,
	0x8d, 0x30, 0x4c, 0xa3, 0xf7, 0x48, 0x25, 0xab, 0x0b, 0x9d, 0x9a, 0x6b, 0xb5, 0x1a, 0x9d, 0xcd,
	0xd9, 0x8b, 0xc1, 0xde, 0x2f, 0xce, 0x62, 0x60, 0x79, 0x36, 0xdd, 0x21, 0x8d, 0x40, 0x46, 0x03,
	0x48, 0x14, 0x5a, 0xe7, 0x28, 0x74, 0x08, 0xea, 0x9e, 0x8a, 0x7a, 0xdb, 0x64, 0xe5, 0x09, 0x68,
	0xd3, 0x86, 0xc1, 0xfb, 0x14, 0xd4, 0x95, 0x85, 0x7a, 0x87, 0x84, 0x16, 0x93, 0x54, 0x2c, 0x23,
	0x05, 0xd4, 0xcf, 0x56, 0x89, 0x21, 0x73, 0xb4, 0xf5, 0x99, 0xda, 0xd8, 0x28, 0xcb, 0xfb, 0x6a,
	0x15, 0xfb, 0xa8, 0x11, 0x5b, 0x93, 0x54, 0x03, 0xae, 0xa1, 0x2b, 0x93, 0x33, 0xc3, 0x39, 0xc6,
	0x46, 0x89, 0x3d, 0x3e, 0xed, 0x1a, 0xa9, 0xf4, 0x44, 0x5f, 0xe4, 0xc7, 0xab, 0xb0, 0x1c, 0x64,
	0x26, 0x8d, 0x79, 0x37, 0xf7, 0x5a, 0x85, 0xe1, 0x73, 0x76, 0x18, 0x25, 0x13, 0xbd, 0x7f, 0x86,
	0x07, 0xab, 0x31, 0x83, 0xb2, 0xc5, 0x88, 0x28, 0xe8, 0xa5, 0x21, 0xa8, 0xc7, 0x02, 0x7a, 0xa1,
	0xc2, 0xc3, 0xd5, 0xd8, 0x54, 0xd4, 0xfb, 0x62, 0x91, 0xd5, 0x09, 0xb1, 0x66, 0xea, 0x5b, 0xa4,
	0x1c, 0x72, 0xcd, 0x1d, 0xcb, 0x2d, 0x5d, 0x3f, 0x32, 0xa6, 0x64, 0x62, 0x03, 0x99, 0x46, 0x1a,
	0xf5, 0x57, 0x58, 0x0e, 0xfe, 0x7d, 0x04, 0xef, 0x90, 0xac, 0x1a, 0xa2, 0x63, 0xa9, 0xc5, 0x6b,
	0x11, 0xe0, 0x31, 0xd1, 0x8a, 0xbc, 0x97, 0x82, 0x42, 0x6d, 0x35, 0x66, 0x50, 0xc1, 0xba, 0x76,
	0xd1, 0xba, 0xde, 0x37, 0x8b, 0xac, 0x1d, 0xa0, 0xc1, 0xe7, 0x9f, 0x7f, 0xe2, 0x40, 0xf6, 0xd4,
	0x81, 0x0a, 0x26, 0x28, 0xfd, 0x89, 0x09, 0xe8, 0x21, 0x59, 0x8a, 0x0a, 0xaa, 0x71, 0xe0, 0x7a,
	0x67, 0x6b, 0x66, 0x55, 0x71, 0x3c, 0x36, 0x51, 0xe6, 0x3d, 0x25, 0xeb, 0x53, 0xda, 0xff, 0xd2,
	0x95, 0x9d, 0x5f, 0x36, 0x69, 0x98, 0xe0, 0x09, 0x24, 0x03, 0x11, 0x00, 0xfd, 0x64, 0x91, 0xe5,
	0x89, 0xee, 0xd4, 0x9b, 0x6a, 0x32, 0x63, 0x6d, 0xcd, 0xed, 0xb9, 0x39, 0xb9, 0x3c, 0x6f, 0xf7,
	0xe3, 0x8f, 0x9f, 0x9f, 0xed, 0x1d, 0x6f, 0x0b, 0x7f, 0xdb, 0x8d, 0x06, 0xe5, 0x07, 0x5c, 0xfb,
	0xe7, 0xa3, 0xa5, 0x5e, 0xf8, 0xe7, 0x22, 0xbc, 0x78, 0x60, 0xdd, 0xa6, 0x1f, 0x48, 0xbd, 0xe0,
	0x41, 0xea, 0x4e, 0x32, 0x5c, 0xfd, 0x2e, 0x35, 0xb7, 0xe6, 0x64, 0x18, 0x05, 0x77, 0x50, 0xc1,
	0x4d, 0xba, 0x8d, 0x0a, 0xe2, 0xb9, 0x1a, 0xe8, 0x73, 0x42, 0x2e, 0x7b, 0xd0, 0xcd, 0xeb, 0xba,
	0x8f, 0xe8, 0xdd, 0xeb, 0x13, 0x0c, 0xfb, 0x7f, 0xfb, 0x8d, 0x57, 0x13, 0xff, 0x75, 0xa7, 0x0b,
	0xf8, 0x71, 0xf7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x22, 0xab, 0x35, 0x11, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentServiceClient interface {
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error)
}

type commentServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommentServiceClient(cc *grpc.ClientConn) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CommentService/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CommentService/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*GetCommentResponse, error) {
	out := new(GetCommentResponse)
	err := c.cc.Invoke(ctx, "/discussproto.CommentService/GetComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
type CommentServiceServer interface {
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)
	GetComment(context.Context, *GetCommentRequest) (*GetCommentResponse, error)
}

func RegisterCommentServiceServer(s *grpc.Server, srv CommentServiceServer) {
	s.RegisterService(&_CommentService_serviceDesc, srv)
}

func _CommentService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CommentService/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CommentService/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.CommentService/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discussproto.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentService_CreateComment_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _CommentService_GetComments_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _CommentService_GetComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
