// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conversation.proto

package discussproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Conversation_State int32

const (
	Conversation_PENDING  Conversation_State = 0
	Conversation_ACCEPTED Conversation_State = 1
	Conversation_REJECTED Conversation_State = 2
)

var Conversation_State_name = map[int32]string{
	0: "PENDING",
	1: "ACCEPTED",
	2: "REJECTED",
}

var Conversation_State_value = map[string]int32{
	"PENDING":  0,
	"ACCEPTED": 1,
	"REJECTED": 2,
}

func (x Conversation_State) String() string {
	return proto.EnumName(Conversation_State_name, int32(x))
}

func (Conversation_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1, 0}
}

type ConversationEntry struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	SubmittedAt          string   `protobuf:"bytes,4,opt,name=submittedAt,proto3" json:"submittedAt,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	UserId               int64    `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	ConversationId       int64    `protobuf:"varint,7,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	Links                []*Link  `protobuf:"bytes,8,rep,name=Links,proto3" json:"Links,omitempty"`
	IsDraft              bool     `protobuf:"varint,9,opt,name=isDraft,proto3" json:"isDraft,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConversationEntry) Reset()         { *m = ConversationEntry{} }
func (m *ConversationEntry) String() string { return proto.CompactTextString(m) }
func (*ConversationEntry) ProtoMessage()    {}
func (*ConversationEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{0}
}

func (m *ConversationEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConversationEntry.Unmarshal(m, b)
}
func (m *ConversationEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConversationEntry.Marshal(b, m, deterministic)
}
func (m *ConversationEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationEntry.Merge(m, src)
}
func (m *ConversationEntry) XXX_Size() int {
	return xxx_messageInfo_ConversationEntry.Size(m)
}
func (m *ConversationEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationEntry proto.InternalMessageInfo

func (m *ConversationEntry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ConversationEntry) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ConversationEntry) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ConversationEntry) GetSubmittedAt() string {
	if m != nil {
		return m.SubmittedAt
	}
	return ""
}

func (m *ConversationEntry) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ConversationEntry) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ConversationEntry) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *ConversationEntry) GetLinks() []*Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ConversationEntry) GetIsDraft() bool {
	if m != nil {
		return m.IsDraft
	}
	return false
}

type Conversation struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Users                []*User              `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	Link                 *Link                `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	Entries              []*ConversationEntry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	State                Conversation_State   `protobuf:"varint,7,opt,name=state,proto3,enum=discussproto.Conversation_State" json:"state,omitempty"`
	OwnerId              int64                `protobuf:"varint,8,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Turn                 int64                `protobuf:"varint,9,opt,name=turn,proto3" json:"turn,omitempty"`
	CreatedAt            string               `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string               `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{1}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Conversation) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Conversation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Conversation) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Conversation) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *Conversation) GetEntries() []*ConversationEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Conversation) GetState() Conversation_State {
	if m != nil {
		return m.State
	}
	return Conversation_PENDING
}

func (m *Conversation) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Conversation) GetTurn() int64 {
	if m != nil {
		return m.Turn
	}
	return 0
}

func (m *Conversation) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Conversation) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

// IO
type GetByUserIDMessage struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIDMessage) Reset()         { *m = GetByUserIDMessage{} }
func (m *GetByUserIDMessage) String() string { return proto.CompactTextString(m) }
func (*GetByUserIDMessage) ProtoMessage()    {}
func (*GetByUserIDMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{2}
}

func (m *GetByUserIDMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIDMessage.Unmarshal(m, b)
}
func (m *GetByUserIDMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIDMessage.Marshal(b, m, deterministic)
}
func (m *GetByUserIDMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIDMessage.Merge(m, src)
}
func (m *GetByUserIDMessage) XXX_Size() int {
	return xxx_messageInfo_GetByUserIDMessage.Size(m)
}
func (m *GetByUserIDMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIDMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIDMessage proto.InternalMessageInfo

func (m *GetByUserIDMessage) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetByUserIDMessage) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetByUserIDMessage) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetByUserIDResponse struct {
	ConversationList     []*Conversation `protobuf:"bytes,1,rep,name=conversationList,proto3" json:"conversationList,omitempty"`
	Page                 int32           `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32           `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetByUserIDResponse) Reset()         { *m = GetByUserIDResponse{} }
func (m *GetByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetByUserIDResponse) ProtoMessage()    {}
func (*GetByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{3}
}

func (m *GetByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIDResponse.Unmarshal(m, b)
}
func (m *GetByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIDResponse.Marshal(b, m, deterministic)
}
func (m *GetByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIDResponse.Merge(m, src)
}
func (m *GetByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetByUserIDResponse.Size(m)
}
func (m *GetByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIDResponse proto.InternalMessageInfo

func (m *GetByUserIDResponse) GetConversationList() []*Conversation {
	if m != nil {
		return m.ConversationList
	}
	return nil
}

func (m *GetByUserIDResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetByUserIDResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetByUserIDResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetByUserMeMessage struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserMeMessage) Reset()         { *m = GetByUserMeMessage{} }
func (m *GetByUserMeMessage) String() string { return proto.CompactTextString(m) }
func (*GetByUserMeMessage) ProtoMessage()    {}
func (*GetByUserMeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{4}
}

func (m *GetByUserMeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserMeMessage.Unmarshal(m, b)
}
func (m *GetByUserMeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserMeMessage.Marshal(b, m, deterministic)
}
func (m *GetByUserMeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserMeMessage.Merge(m, src)
}
func (m *GetByUserMeMessage) XXX_Size() int {
	return xxx_messageInfo_GetByUserMeMessage.Size(m)
}
func (m *GetByUserMeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserMeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserMeMessage proto.InternalMessageInfo

func (m *GetByUserMeMessage) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetByUserMeMessage) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetByUserMeResponse struct {
	ConversationList     []*Conversation `protobuf:"bytes,1,rep,name=conversationList,proto3" json:"conversationList,omitempty"`
	Page                 int32           `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32           `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetByUserMeResponse) Reset()         { *m = GetByUserMeResponse{} }
func (m *GetByUserMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetByUserMeResponse) ProtoMessage()    {}
func (*GetByUserMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{5}
}

func (m *GetByUserMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserMeResponse.Unmarshal(m, b)
}
func (m *GetByUserMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserMeResponse.Marshal(b, m, deterministic)
}
func (m *GetByUserMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserMeResponse.Merge(m, src)
}
func (m *GetByUserMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetByUserMeResponse.Size(m)
}
func (m *GetByUserMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserMeResponse proto.InternalMessageInfo

func (m *GetByUserMeResponse) GetConversationList() []*Conversation {
	if m != nil {
		return m.ConversationList
	}
	return nil
}

func (m *GetByUserMeResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetByUserMeResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetByUserMeResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetByIDMessage struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDMessage) Reset()         { *m = GetByIDMessage{} }
func (m *GetByIDMessage) String() string { return proto.CompactTextString(m) }
func (*GetByIDMessage) ProtoMessage()    {}
func (*GetByIDMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{6}
}

func (m *GetByIDMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDMessage.Unmarshal(m, b)
}
func (m *GetByIDMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDMessage.Marshal(b, m, deterministic)
}
func (m *GetByIDMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDMessage.Merge(m, src)
}
func (m *GetByIDMessage) XXX_Size() int {
	return xxx_messageInfo_GetByIDMessage.Size(m)
}
func (m *GetByIDMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDMessage proto.InternalMessageInfo

func (m *GetByIDMessage) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type GetByIDResponse struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetByIDResponse) Reset()         { *m = GetByIDResponse{} }
func (m *GetByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetByIDResponse) ProtoMessage()    {}
func (*GetByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{7}
}

func (m *GetByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDResponse.Unmarshal(m, b)
}
func (m *GetByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDResponse.Merge(m, src)
}
func (m *GetByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetByIDResponse.Size(m)
}
func (m *GetByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDResponse proto.InternalMessageInfo

func (m *GetByIDResponse) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type CreateConversationEntryRequest struct {
	ConversationId       int64              `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationEntry    *ConversationEntry `protobuf:"bytes,2,opt,name=conversationEntry,proto3" json:"conversationEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateConversationEntryRequest) Reset()         { *m = CreateConversationEntryRequest{} }
func (m *CreateConversationEntryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationEntryRequest) ProtoMessage()    {}
func (*CreateConversationEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{8}
}

func (m *CreateConversationEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationEntryRequest.Unmarshal(m, b)
}
func (m *CreateConversationEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationEntryRequest.Marshal(b, m, deterministic)
}
func (m *CreateConversationEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationEntryRequest.Merge(m, src)
}
func (m *CreateConversationEntryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationEntryRequest.Size(m)
}
func (m *CreateConversationEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationEntryRequest proto.InternalMessageInfo

func (m *CreateConversationEntryRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *CreateConversationEntryRequest) GetConversationEntry() *ConversationEntry {
	if m != nil {
		return m.ConversationEntry
	}
	return nil
}

type CreateConversationEntryResponse struct {
	ConversationEntry    *ConversationEntry `protobuf:"bytes,1,opt,name=conversationEntry,proto3" json:"conversationEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateConversationEntryResponse) Reset()         { *m = CreateConversationEntryResponse{} }
func (m *CreateConversationEntryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationEntryResponse) ProtoMessage()    {}
func (*CreateConversationEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{9}
}

func (m *CreateConversationEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationEntryResponse.Unmarshal(m, b)
}
func (m *CreateConversationEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationEntryResponse.Marshal(b, m, deterministic)
}
func (m *CreateConversationEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationEntryResponse.Merge(m, src)
}
func (m *CreateConversationEntryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationEntryResponse.Size(m)
}
func (m *CreateConversationEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationEntryResponse proto.InternalMessageInfo

func (m *CreateConversationEntryResponse) GetConversationEntry() *ConversationEntry {
	if m != nil {
		return m.ConversationEntry
	}
	return nil
}

type UpdateConversationEntryRequest struct {
	ConversationEntryId  int64    `protobuf:"varint,1,opt,name=conversationEntryId,proto3" json:"conversationEntryId,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ConversationId       int64    `protobuf:"varint,3,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConversationEntryRequest) Reset()         { *m = UpdateConversationEntryRequest{} }
func (m *UpdateConversationEntryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationEntryRequest) ProtoMessage()    {}
func (*UpdateConversationEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{10}
}

func (m *UpdateConversationEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationEntryRequest.Unmarshal(m, b)
}
func (m *UpdateConversationEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationEntryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConversationEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationEntryRequest.Merge(m, src)
}
func (m *UpdateConversationEntryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationEntryRequest.Size(m)
}
func (m *UpdateConversationEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationEntryRequest proto.InternalMessageInfo

func (m *UpdateConversationEntryRequest) GetConversationEntryId() int64 {
	if m != nil {
		return m.ConversationEntryId
	}
	return 0
}

func (m *UpdateConversationEntryRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateConversationEntryRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type UpdateConversationEntryResponse struct {
	ConversationEntry    *ConversationEntry `protobuf:"bytes,1,opt,name=conversationEntry,proto3" json:"conversationEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateConversationEntryResponse) Reset()         { *m = UpdateConversationEntryResponse{} }
func (m *UpdateConversationEntryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationEntryResponse) ProtoMessage()    {}
func (*UpdateConversationEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{11}
}

func (m *UpdateConversationEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationEntryResponse.Unmarshal(m, b)
}
func (m *UpdateConversationEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationEntryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConversationEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationEntryResponse.Merge(m, src)
}
func (m *UpdateConversationEntryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationEntryResponse.Size(m)
}
func (m *UpdateConversationEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationEntryResponse proto.InternalMessageInfo

func (m *UpdateConversationEntryResponse) GetConversationEntry() *ConversationEntry {
	if m != nil {
		return m.ConversationEntry
	}
	return nil
}

type SubmitConversationEntryRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationEntryId  int64    `protobuf:"varint,2,opt,name=conversationEntryId,proto3" json:"conversationEntryId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitConversationEntryRequest) Reset()         { *m = SubmitConversationEntryRequest{} }
func (m *SubmitConversationEntryRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitConversationEntryRequest) ProtoMessage()    {}
func (*SubmitConversationEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{12}
}

func (m *SubmitConversationEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitConversationEntryRequest.Unmarshal(m, b)
}
func (m *SubmitConversationEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitConversationEntryRequest.Marshal(b, m, deterministic)
}
func (m *SubmitConversationEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitConversationEntryRequest.Merge(m, src)
}
func (m *SubmitConversationEntryRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitConversationEntryRequest.Size(m)
}
func (m *SubmitConversationEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitConversationEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitConversationEntryRequest proto.InternalMessageInfo

func (m *SubmitConversationEntryRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *SubmitConversationEntryRequest) GetConversationEntryId() int64 {
	if m != nil {
		return m.ConversationEntryId
	}
	return 0
}

type SubmitConversationEntryResponse struct {
	ConversationEntry    *ConversationEntry `protobuf:"bytes,1,opt,name=conversationEntry,proto3" json:"conversationEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubmitConversationEntryResponse) Reset()         { *m = SubmitConversationEntryResponse{} }
func (m *SubmitConversationEntryResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitConversationEntryResponse) ProtoMessage()    {}
func (*SubmitConversationEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{13}
}

func (m *SubmitConversationEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitConversationEntryResponse.Unmarshal(m, b)
}
func (m *SubmitConversationEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitConversationEntryResponse.Marshal(b, m, deterministic)
}
func (m *SubmitConversationEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitConversationEntryResponse.Merge(m, src)
}
func (m *SubmitConversationEntryResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitConversationEntryResponse.Size(m)
}
func (m *SubmitConversationEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitConversationEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitConversationEntryResponse proto.InternalMessageInfo

func (m *SubmitConversationEntryResponse) GetConversationEntry() *ConversationEntry {
	if m != nil {
		return m.ConversationEntry
	}
	return nil
}

type GetConversationEntryDraftRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationEntryDraftRequest) Reset()         { *m = GetConversationEntryDraftRequest{} }
func (m *GetConversationEntryDraftRequest) String() string { return proto.CompactTextString(m) }
func (*GetConversationEntryDraftRequest) ProtoMessage()    {}
func (*GetConversationEntryDraftRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{14}
}

func (m *GetConversationEntryDraftRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationEntryDraftRequest.Unmarshal(m, b)
}
func (m *GetConversationEntryDraftRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationEntryDraftRequest.Marshal(b, m, deterministic)
}
func (m *GetConversationEntryDraftRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationEntryDraftRequest.Merge(m, src)
}
func (m *GetConversationEntryDraftRequest) XXX_Size() int {
	return xxx_messageInfo_GetConversationEntryDraftRequest.Size(m)
}
func (m *GetConversationEntryDraftRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationEntryDraftRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationEntryDraftRequest proto.InternalMessageInfo

func (m *GetConversationEntryDraftRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type GetConversationEntryDraftResponse struct {
	ConversationEntry    *ConversationEntry `protobuf:"bytes,1,opt,name=conversationEntry,proto3" json:"conversationEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetConversationEntryDraftResponse) Reset()         { *m = GetConversationEntryDraftResponse{} }
func (m *GetConversationEntryDraftResponse) String() string { return proto.CompactTextString(m) }
func (*GetConversationEntryDraftResponse) ProtoMessage()    {}
func (*GetConversationEntryDraftResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{15}
}

func (m *GetConversationEntryDraftResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationEntryDraftResponse.Unmarshal(m, b)
}
func (m *GetConversationEntryDraftResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationEntryDraftResponse.Marshal(b, m, deterministic)
}
func (m *GetConversationEntryDraftResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationEntryDraftResponse.Merge(m, src)
}
func (m *GetConversationEntryDraftResponse) XXX_Size() int {
	return xxx_messageInfo_GetConversationEntryDraftResponse.Size(m)
}
func (m *GetConversationEntryDraftResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationEntryDraftResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationEntryDraftResponse proto.InternalMessageInfo

func (m *GetConversationEntryDraftResponse) GetConversationEntry() *ConversationEntry {
	if m != nil {
		return m.ConversationEntry
	}
	return nil
}

type GetConversationEntriesRequest struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,4,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,5,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConversationEntriesRequest) Reset()         { *m = GetConversationEntriesRequest{} }
func (m *GetConversationEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetConversationEntriesRequest) ProtoMessage()    {}
func (*GetConversationEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{16}
}

func (m *GetConversationEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationEntriesRequest.Unmarshal(m, b)
}
func (m *GetConversationEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationEntriesRequest.Marshal(b, m, deterministic)
}
func (m *GetConversationEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationEntriesRequest.Merge(m, src)
}
func (m *GetConversationEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetConversationEntriesRequest.Size(m)
}
func (m *GetConversationEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationEntriesRequest proto.InternalMessageInfo

func (m *GetConversationEntriesRequest) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

func (m *GetConversationEntriesRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetConversationEntriesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetConversationEntriesRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetConversationEntriesRequest) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetConversationEntriesResponse struct {
	Data                 []*ConversationEntry `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page                 int32                `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32                `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string               `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string               `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetConversationEntriesResponse) Reset()         { *m = GetConversationEntriesResponse{} }
func (m *GetConversationEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetConversationEntriesResponse) ProtoMessage()    {}
func (*GetConversationEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{17}
}

func (m *GetConversationEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConversationEntriesResponse.Unmarshal(m, b)
}
func (m *GetConversationEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConversationEntriesResponse.Marshal(b, m, deterministic)
}
func (m *GetConversationEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConversationEntriesResponse.Merge(m, src)
}
func (m *GetConversationEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetConversationEntriesResponse.Size(m)
}
func (m *GetConversationEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConversationEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConversationEntriesResponse proto.InternalMessageInfo

func (m *GetConversationEntriesResponse) GetData() []*ConversationEntry {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetConversationEntriesResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetConversationEntriesResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetConversationEntriesResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetConversationEntriesResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetConversationEntriesResponse) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetAllRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy               string   `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,4,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{18}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAllRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetAllRequest) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetAllResponse struct {
	ConversationList     []*Conversation `protobuf:"bytes,1,rep,name=conversationList,proto3" json:"conversationList,omitempty"`
	Page                 int32           `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32           `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string          `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string          `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6ae46d001825652, []int{19}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetConversationList() []*Conversation {
	if m != nil {
		return m.ConversationList
	}
	return nil
}

func (m *GetAllResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAllResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAllResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetAllResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetAllResponse) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

func init() {
	proto.RegisterEnum("discussproto.Conversation_State", Conversation_State_name, Conversation_State_value)
	proto.RegisterType((*ConversationEntry)(nil), "discussproto.ConversationEntry")
	proto.RegisterType((*Conversation)(nil), "discussproto.Conversation")
	proto.RegisterType((*GetByUserIDMessage)(nil), "discussproto.GetByUserIDMessage")
	proto.RegisterType((*GetByUserIDResponse)(nil), "discussproto.GetByUserIDResponse")
	proto.RegisterType((*GetByUserMeMessage)(nil), "discussproto.GetByUserMeMessage")
	proto.RegisterType((*GetByUserMeResponse)(nil), "discussproto.GetByUserMeResponse")
	proto.RegisterType((*GetByIDMessage)(nil), "discussproto.GetByIDMessage")
	proto.RegisterType((*GetByIDResponse)(nil), "discussproto.GetByIDResponse")
	proto.RegisterType((*CreateConversationEntryRequest)(nil), "discussproto.CreateConversationEntryRequest")
	proto.RegisterType((*CreateConversationEntryResponse)(nil), "discussproto.CreateConversationEntryResponse")
	proto.RegisterType((*UpdateConversationEntryRequest)(nil), "discussproto.UpdateConversationEntryRequest")
	proto.RegisterType((*UpdateConversationEntryResponse)(nil), "discussproto.UpdateConversationEntryResponse")
	proto.RegisterType((*SubmitConversationEntryRequest)(nil), "discussproto.SubmitConversationEntryRequest")
	proto.RegisterType((*SubmitConversationEntryResponse)(nil), "discussproto.SubmitConversationEntryResponse")
	proto.RegisterType((*GetConversationEntryDraftRequest)(nil), "discussproto.GetConversationEntryDraftRequest")
	proto.RegisterType((*GetConversationEntryDraftResponse)(nil), "discussproto.GetConversationEntryDraftResponse")
	proto.RegisterType((*GetConversationEntriesRequest)(nil), "discussproto.GetConversationEntriesRequest")
	proto.RegisterType((*GetConversationEntriesResponse)(nil), "discussproto.GetConversationEntriesResponse")
	proto.RegisterType((*GetAllRequest)(nil), "discussproto.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "discussproto.GetAllResponse")
}

func init() { proto.RegisterFile("conversation.proto", fileDescriptor_d6ae46d001825652) }

var fileDescriptor_d6ae46d001825652 = []byte{
	// 1164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcf, 0x4f, 0x24, 0x45,
	0x14, 0xb6, 0xe6, 0x17, 0xec, 0x03, 0xd9, 0xdd, 0x62, 0x85, 0x76, 0x96, 0x85, 0xa1, 0x35, 0x64,
	0x54, 0x98, 0xde, 0x80, 0x6e, 0xd4, 0x03, 0x09, 0xcc, 0x8c, 0x64, 0xc8, 0xb2, 0xc1, 0xc6, 0xf5,
	0xe0, 0xc9, 0x66, 0xba, 0x1c, 0x2b, 0x0c, 0xdd, 0x63, 0x57, 0x0d, 0x04, 0x09, 0x17, 0xff, 0x05,
	0x4d, 0x3c, 0x19, 0xcf, 0xc6, 0xe3, 0x1e, 0x3c, 0x7b, 0xf3, 0xee, 0xc1, 0xc4, 0xb3, 0xff, 0x86,
	0x89, 0xa9, 0xd7, 0x3d, 0x43, 0x4f, 0xff, 0x98, 0xe9, 0x95, 0x90, 0xec, 0x89, 0xae, 0x7a, 0xaf,
	0xea, 0x7d, 0xdf, 0x57, 0xaf, 0xea, 0xbd, 0x01, 0x68, 0xdb, 0x75, 0xce, 0x98, 0x27, 0x2c, 0xc9,
	0x5d, 0xa7, 0xd6, 0xf3, 0x5c, 0xe9, 0xd2, 0x59, 0x9b, 0x8b, 0x76, 0x5f, 0x08, 0x1c, 0x95, 0xa1,
	0xcb, 0x9d, 0x93, 0x5a, 0xf0, 0xdd, 0x17, 0xcc, 0x0b, 0xbe, 0x97, 0x3a, 0xae, 0xdb, 0xe9, 0x32,
	0xc3, 0xea, 0x71, 0xc3, 0x72, 0x1c, 0x57, 0xe2, 0x16, 0x22, 0xb0, 0x3e, 0xe9, 0x70, 0xf9, 0x75,
	0xff, 0xb8, 0xd6, 0x76, 0x4f, 0x8d, 0xd3, 0x73, 0x2e, 0x4f, 0xdc, 0x73, 0xa3, 0xe3, 0x6e, 0xa0,
	0x71, 0xe3, 0xcc, 0xea, 0x72, 0xdb, 0x92, 0xae, 0x27, 0x8c, 0xe1, 0xa7, 0xbf, 0x4e, 0xff, 0x39,
	0x07, 0xf7, 0xeb, 0x21, 0x48, 0x4d, 0x47, 0x7a, 0x17, 0x74, 0x0e, 0x72, 0xdc, 0xd6, 0x48, 0x85,
	0x54, 0xf3, 0x66, 0x8e, 0xdb, 0x74, 0x09, 0xee, 0xb4, 0x3d, 0x66, 0x49, 0x66, 0xef, 0x48, 0x2d,
	0x57, 0x21, 0xd5, 0x3b, 0xe6, 0xf5, 0x84, 0xb2, 0xf6, 0x7b, 0x76, 0x60, 0xcd, 0xfb, 0xd6, 0xe1,
	0x04, 0xad, 0xc0, 0x8c, 0xe8, 0x1f, 0x9f, 0x72, 0xe9, 0xdb, 0x0b, 0x68, 0x0f, 0x4f, 0x51, 0x0d,
	0xa6, 0xda, 0xae, 0x23, 0x99, 0x23, 0xb5, 0x22, 0x5a, 0x07, 0x43, 0xba, 0x00, 0x25, 0xa5, 0x40,
	0xcb, 0xd6, 0x4a, 0x88, 0x25, 0x18, 0xd1, 0x35, 0x98, 0x0b, 0xeb, 0xd8, 0xb2, 0xb5, 0x29, 0xb4,
	0x47, 0x66, 0x69, 0x15, 0x8a, 0x4f, 0xb9, 0x73, 0x22, 0xb4, 0xe9, 0x4a, 0xbe, 0x3a, 0xb3, 0x49,
	0x6b, 0x61, 0xa5, 0x6b, 0xca, 0x64, 0xfa, 0x0e, 0x0a, 0x03, 0x17, 0x0d, 0xcf, 0xfa, 0x4a, 0x6a,
	0x77, 0x2a, 0xa4, 0x3a, 0x6d, 0x0e, 0x86, 0xfa, 0x6f, 0x79, 0x98, 0x0d, 0x2b, 0x14, 0x13, 0xe7,
	0x01, 0x14, 0x25, 0x97, 0x5d, 0x16, 0x08, 0xe3, 0x0f, 0x14, 0x6d, 0x9b, 0x89, 0xb6, 0xc7, 0x7b,
	0x6a, 0x51, 0x20, 0x4b, 0x78, 0x4a, 0x81, 0x53, 0x74, 0x84, 0x56, 0x48, 0x02, 0xf7, 0x5c, 0x30,
	0xcf, 0xf4, 0x1d, 0xe8, 0x1a, 0x14, 0x54, 0x52, 0xa0, 0x3a, 0xc9, 0x2c, 0xd0, 0x4e, 0x3f, 0x82,
	0x29, 0xe6, 0x48, 0x8f, 0x33, 0xa1, 0x95, 0x70, 0xcf, 0x95, 0x51, 0xd7, 0xd8, 0x41, 0x9b, 0x03,
	0x7f, 0xfa, 0x04, 0x8a, 0x42, 0x5a, 0x92, 0xa1, 0x90, 0x73, 0x9b, 0x95, 0xf4, 0x85, 0xb5, 0x23,
	0xe5, 0x67, 0xfa, 0xee, 0x4a, 0x37, 0xf7, 0xdc, 0xc1, 0x23, 0x9a, 0x46, 0x45, 0x06, 0x43, 0x4a,
	0xa1, 0x20, 0xfb, 0x9e, 0x83, 0x72, 0xe6, 0x4d, 0xfc, 0x1e, 0xcd, 0x23, 0x18, 0x9b, 0x47, 0x33,
	0x91, 0x3c, 0xd2, 0x1f, 0x43, 0x11, 0x23, 0xd3, 0x19, 0x98, 0x3a, 0x6c, 0x3e, 0x6b, 0xb4, 0x9e,
	0xed, 0xdd, 0x7b, 0x8d, 0xce, 0xc2, 0xf4, 0x4e, 0xbd, 0xde, 0x3c, 0xfc, 0xac, 0xd9, 0xb8, 0x47,
	0xd4, 0xc8, 0x6c, 0xee, 0x37, 0xeb, 0x6a, 0x94, 0xd3, 0x3f, 0x07, 0xba, 0xc7, 0xe4, 0xee, 0x85,
	0x92, 0xb2, 0xd5, 0x38, 0x60, 0x42, 0x58, 0x1d, 0x16, 0xca, 0x29, 0x32, 0x92, 0x53, 0x14, 0x0a,
	0x3d, 0xab, 0xe3, 0x9f, 0x62, 0xd1, 0xc4, 0x6f, 0x75, 0xb4, 0x5d, 0x7e, 0xca, 0xfd, 0xac, 0x2e,
	0x9a, 0xfe, 0x40, 0xff, 0x89, 0xc0, 0x7c, 0x68, 0x63, 0x93, 0x89, 0x9e, 0xeb, 0x08, 0x46, 0x3f,
	0x81, 0x7b, 0xe1, 0xfc, 0x7b, 0xca, 0x85, 0xd4, 0x08, 0x9e, 0x43, 0x39, 0x5d, 0x4e, 0x33, 0xb6,
	0x26, 0x3b, 0x12, 0x35, 0xdb, 0x76, 0xfb, 0x8e, 0x7f, 0xab, 0x8a, 0xa6, 0x3f, 0xd0, 0xb7, 0x43,
	0xbc, 0x0f, 0xd8, 0x80, 0xf7, 0x60, 0x57, 0x92, 0xb4, 0x6b, 0x2e, 0x95, 0xdf, 0x01, 0x7b, 0xe5,
	0xf8, 0x7d, 0x08, 0x73, 0x08, 0xef, 0xfa, 0x4c, 0xe3, 0xef, 0x01, 0x49, 0x7a, 0x0f, 0xf4, 0x4f,
	0xe1, 0x6e, 0xb0, 0x72, 0x48, 0x6a, 0x1b, 0x66, 0xc3, 0x4e, 0xb8, 0x70, 0x3c, 0xa1, 0x11, 0x7f,
	0xfd, 0x47, 0x02, 0xcb, 0x75, 0x4c, 0xe1, 0xf8, 0xed, 0x62, 0xdf, 0xf4, 0x99, 0x90, 0x59, 0xd1,
	0xd1, 0x03, 0xb8, 0xdf, 0x8e, 0xee, 0x81, 0x22, 0x65, 0xb8, 0xc8, 0xf1, 0x95, 0x7a, 0x0f, 0x56,
	0x52, 0x81, 0x05, 0xe4, 0x13, 0x23, 0x92, 0xff, 0x1d, 0xf1, 0x07, 0x02, 0xcb, 0xcf, 0xf1, 0xc2,
	0xa6, 0x6a, 0xf1, 0x18, 0xe6, 0x63, 0xeb, 0x86, 0x82, 0x24, 0x99, 0xc2, 0xd5, 0x21, 0x37, 0x5a,
	0x1d, 0xe2, 0xba, 0xe6, 0x13, 0x4f, 0xbd, 0x07, 0x2b, 0xa9, 0xa8, 0x6e, 0x47, 0x88, 0x6f, 0x61,
	0xf9, 0x08, 0x0b, 0xdc, 0x8d, 0x73, 0x22, 0x45, 0xaf, 0x5c, 0xaa, 0x5e, 0x8a, 0x6d, 0x6a, 0xec,
	0xdb, 0x61, 0xbb, 0x0f, 0x95, 0x3d, 0x16, 0x0f, 0x87, 0xe5, 0xf3, 0x25, 0xf9, 0xea, 0x1e, 0xac,
	0x8e, 0xd9, 0xeb, 0x76, 0xf0, 0xbf, 0x20, 0xf0, 0x28, 0x21, 0x28, 0x67, 0xe2, 0x65, 0x4f, 0x2b,
	0xfb, 0xcb, 0xb6, 0x00, 0x25, 0xe1, 0x7a, 0x72, 0xf7, 0x22, 0x68, 0x88, 0x82, 0x11, 0xad, 0xc2,
	0x5d, 0xff, 0xab, 0xc1, 0x3d, 0xd6, 0xc6, 0x17, 0xc9, 0xef, 0x89, 0xa2, 0xd3, 0xfa, 0x5f, 0x04,
	0x96, 0xd3, 0x50, 0x07, 0x3a, 0x6d, 0x41, 0xc1, 0xb6, 0xa4, 0x15, 0x3c, 0xd2, 0x13, 0xa5, 0x41,
	0xe7, 0x9b, 0xbe, 0xce, 0x21, 0x66, 0xc5, 0x49, 0xcc, 0x4a, 0xc9, 0xcc, 0x2e, 0xe1, 0xf5, 0x3d,
	0x26, 0x77, 0xba, 0xdd, 0x81, 0xfc, 0x99, 0x4b, 0x57, 0x28, 0x78, 0x7e, 0x52, 0xf0, 0x42, 0x72,
	0xf0, 0xbf, 0x09, 0x56, 0x17, 0x8c, 0xfe, 0x6a, 0xd5, 0xbd, 0x9b, 0x2b, 0xbb, 0xf9, 0x2f, 0xc0,
	0x7c, 0x18, 0xe4, 0x11, 0xf3, 0xce, 0x78, 0x9b, 0xd1, 0x2f, 0xa1, 0xe4, 0x73, 0xa6, 0x0f, 0x47,
	0x19, 0x8d, 0x9c, 0x43, 0x79, 0x29, 0xd9, 0xe8, 0xcb, 0xa4, 0x3f, 0xfc, 0xee, 0xcf, 0x7f, 0xbe,
	0xcf, 0xbd, 0x41, 0xe7, 0xf1, 0x27, 0x4a, 0xcf, 0x08, 0xf3, 0xa7, 0x3d, 0x98, 0x09, 0xb5, 0x14,
	0xb4, 0x12, 0xdb, 0x29, 0xd2, 0xae, 0x94, 0x57, 0x53, 0x3d, 0x86, 0x01, 0x97, 0x30, 0xe0, 0x02,
	0x7d, 0x80, 0x01, 0xc3, 0xe1, 0x8c, 0x53, 0x46, 0xaf, 0x42, 0x11, 0x5b, 0x8d, 0xd4, 0x88, 0xc3,
	0x26, 0x22, 0x35, 0xe2, 0x75, 0xb3, 0xa0, 0xbf, 0x83, 0x11, 0xdf, 0xa2, 0xab, 0x09, 0x14, 0x0d,
	0xd5, 0x47, 0x1a, 0x97, 0x7e, 0x37, 0x79, 0x45, 0x25, 0x4c, 0x05, 0xad, 0x06, 0x5d, 0x4a, 0xd8,
	0xf8, 0x3a, 0xec, 0xa3, 0x44, 0xeb, 0x30, 0xe4, 0x3a, 0x86, 0x5c, 0xa3, 0x6f, 0x27, 0x85, 0xbc,
	0x1c, 0x7d, 0x7f, 0xae, 0xe8, 0xaf, 0x04, 0x16, 0x53, 0x8a, 0x3e, 0x5d, 0x8f, 0x24, 0xeb, 0xd8,
	0xa6, 0xa5, 0xbc, 0x91, 0xd1, 0x3b, 0x80, 0xb9, 0x85, 0x30, 0x37, 0xf4, 0x6a, 0xfc, 0x2c, 0xa2,
	0x20, 0x0d, 0xf5, 0x9b, 0xe3, 0xe2, 0x63, 0xf2, 0x2e, 0xfd, 0x9d, 0xc0, 0x62, 0x4a, 0x65, 0x8e,
	0xa2, 0x1d, 0xdf, 0x56, 0x44, 0xd1, 0x4e, 0x28, 0xf7, 0x7a, 0x0b, 0xd1, 0xd6, 0x37, 0xb7, 0xb3,
	0xa2, 0x1d, 0x9d, 0x0e, 0x4a, 0xed, 0x95, 0xe2, 0xf0, 0x07, 0x81, 0xc5, 0x94, 0x7a, 0x1b, 0xe5,
	0x30, 0xbe, 0x25, 0x88, 0x72, 0x98, 0x50, 0xc4, 0xf5, 0x43, 0xe4, 0xb0, 0xaf, 0x37, 0x6f, 0xc6,
	0xc1, 0xf0, 0x7f, 0x89, 0x2b, 0x2a, 0x2f, 0x08, 0xbc, 0x99, 0x5a, 0x7c, 0x69, 0x2d, 0x96, 0xa7,
	0x63, 0x2b, 0x7e, 0xd9, 0xc8, 0xec, 0x1f, 0x10, 0xfa, 0x00, 0x09, 0x19, 0x74, 0x23, 0x03, 0x21,
	0xbc, 0x6b, 0x36, 0xe2, 0xfa, 0x85, 0xc0, 0x42, 0x72, 0x1d, 0xa4, 0xef, 0x4d, 0x84, 0x70, 0x5d,
	0xe3, 0xcb, 0xeb, 0xd9, 0x9c, 0x03, 0xb0, 0xef, 0x23, 0xd8, 0x1a, 0x5d, 0xcf, 0x72, 0x2d, 0x8d,
	0xe0, 0x57, 0xf6, 0xee, 0xdc, 0x17, 0x23, 0xff, 0xeb, 0x39, 0x2e, 0xe1, 0x9f, 0xad, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x19, 0xc4, 0xee, 0xcd, 0x16, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConversationServiceClient is the client API for ConversationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConversationServiceClient interface {
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetByUserMe(ctx context.Context, in *GetByUserMeMessage, opts ...grpc.CallOption) (*GetByUserMeResponse, error)
	GetByUserID(ctx context.Context, in *GetByUserIDMessage, opts ...grpc.CallOption) (*GetByUserIDResponse, error)
	GetByID(ctx context.Context, in *GetByIDMessage, opts ...grpc.CallOption) (*GetByIDResponse, error)
	CreateConversationEntry(ctx context.Context, in *CreateConversationEntryRequest, opts ...grpc.CallOption) (*CreateConversationEntryResponse, error)
	UpdateConversationEntry(ctx context.Context, in *UpdateConversationEntryRequest, opts ...grpc.CallOption) (*UpdateConversationEntryResponse, error)
	SubmitConversationEntry(ctx context.Context, in *SubmitConversationEntryRequest, opts ...grpc.CallOption) (*SubmitConversationEntryResponse, error)
	GetConversationEntryDraft(ctx context.Context, in *GetConversationEntryDraftRequest, opts ...grpc.CallOption) (*GetConversationEntryDraftResponse, error)
	GetConversationEntries(ctx context.Context, in *GetConversationEntriesRequest, opts ...grpc.CallOption) (*GetConversationEntriesResponse, error)
}

type conversationServiceClient struct {
	cc *grpc.ClientConn
}

func NewConversationServiceClient(cc *grpc.ClientConn) ConversationServiceClient {
	return &conversationServiceClient{cc}
}

func (c *conversationServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetByUserMe(ctx context.Context, in *GetByUserMeMessage, opts ...grpc.CallOption) (*GetByUserMeResponse, error) {
	out := new(GetByUserMeResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetByUserMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetByUserID(ctx context.Context, in *GetByUserIDMessage, opts ...grpc.CallOption) (*GetByUserIDResponse, error) {
	out := new(GetByUserIDResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetByID(ctx context.Context, in *GetByIDMessage, opts ...grpc.CallOption) (*GetByIDResponse, error) {
	out := new(GetByIDResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) CreateConversationEntry(ctx context.Context, in *CreateConversationEntryRequest, opts ...grpc.CallOption) (*CreateConversationEntryResponse, error) {
	out := new(CreateConversationEntryResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/CreateConversationEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) UpdateConversationEntry(ctx context.Context, in *UpdateConversationEntryRequest, opts ...grpc.CallOption) (*UpdateConversationEntryResponse, error) {
	out := new(UpdateConversationEntryResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/UpdateConversationEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) SubmitConversationEntry(ctx context.Context, in *SubmitConversationEntryRequest, opts ...grpc.CallOption) (*SubmitConversationEntryResponse, error) {
	out := new(SubmitConversationEntryResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/SubmitConversationEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversationEntryDraft(ctx context.Context, in *GetConversationEntryDraftRequest, opts ...grpc.CallOption) (*GetConversationEntryDraftResponse, error) {
	out := new(GetConversationEntryDraftResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetConversationEntryDraft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationServiceClient) GetConversationEntries(ctx context.Context, in *GetConversationEntriesRequest, opts ...grpc.CallOption) (*GetConversationEntriesResponse, error) {
	out := new(GetConversationEntriesResponse)
	err := c.cc.Invoke(ctx, "/discussproto.ConversationService/GetConversationEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServiceServer is the server API for ConversationService service.
type ConversationServiceServer interface {
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	GetByUserMe(context.Context, *GetByUserMeMessage) (*GetByUserMeResponse, error)
	GetByUserID(context.Context, *GetByUserIDMessage) (*GetByUserIDResponse, error)
	GetByID(context.Context, *GetByIDMessage) (*GetByIDResponse, error)
	CreateConversationEntry(context.Context, *CreateConversationEntryRequest) (*CreateConversationEntryResponse, error)
	UpdateConversationEntry(context.Context, *UpdateConversationEntryRequest) (*UpdateConversationEntryResponse, error)
	SubmitConversationEntry(context.Context, *SubmitConversationEntryRequest) (*SubmitConversationEntryResponse, error)
	GetConversationEntryDraft(context.Context, *GetConversationEntryDraftRequest) (*GetConversationEntryDraftResponse, error)
	GetConversationEntries(context.Context, *GetConversationEntriesRequest) (*GetConversationEntriesResponse, error)
}

func RegisterConversationServiceServer(s *grpc.Server, srv ConversationServiceServer) {
	s.RegisterService(&_ConversationService_serviceDesc, srv)
}

func _ConversationService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetByUserMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserMeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetByUserMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetByUserMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetByUserMe(ctx, req.(*GetByUserMeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetByUserID(ctx, req.(*GetByUserIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetByID(ctx, req.(*GetByIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_CreateConversationEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).CreateConversationEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/CreateConversationEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).CreateConversationEntry(ctx, req.(*CreateConversationEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_UpdateConversationEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).UpdateConversationEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/UpdateConversationEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).UpdateConversationEntry(ctx, req.(*UpdateConversationEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_SubmitConversationEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitConversationEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).SubmitConversationEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/SubmitConversationEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).SubmitConversationEntry(ctx, req.(*SubmitConversationEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversationEntryDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationEntryDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversationEntryDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetConversationEntryDraft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversationEntryDraft(ctx, req.(*GetConversationEntryDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConversationService_GetConversationEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServiceServer).GetConversationEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.ConversationService/GetConversationEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServiceServer).GetConversationEntries(ctx, req.(*GetConversationEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConversationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discussproto.ConversationService",
	HandlerType: (*ConversationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _ConversationService_GetAll_Handler,
		},
		{
			MethodName: "GetByUserMe",
			Handler:    _ConversationService_GetByUserMe_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _ConversationService_GetByUserID_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _ConversationService_GetByID_Handler,
		},
		{
			MethodName: "CreateConversationEntry",
			Handler:    _ConversationService_CreateConversationEntry_Handler,
		},
		{
			MethodName: "UpdateConversationEntry",
			Handler:    _ConversationService_UpdateConversationEntry_Handler,
		},
		{
			MethodName: "SubmitConversationEntry",
			Handler:    _ConversationService_SubmitConversationEntry_Handler,
		},
		{
			MethodName: "GetConversationEntryDraft",
			Handler:    _ConversationService_GetConversationEntryDraft_Handler,
		},
		{
			MethodName: "GetConversationEntries",
			Handler:    _ConversationService_GetConversationEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conversation.proto",
}
