// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/invitation.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Invitation struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64         `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TwitterScreenName    string        `protobuf:"bytes,3,opt,name=twitterScreenName,proto3" json:"twitterScreenName,omitempty"`
	Name                 string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string        `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Conversation         *Conversation `protobuf:"bytes,6,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Invitation) Reset()         { *m = Invitation{} }
func (m *Invitation) String() string { return proto.CompactTextString(m) }
func (*Invitation) ProtoMessage()    {}
func (*Invitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{0}
}

func (m *Invitation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invitation.Unmarshal(m, b)
}
func (m *Invitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invitation.Marshal(b, m, deterministic)
}
func (m *Invitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invitation.Merge(m, src)
}
func (m *Invitation) XXX_Size() int {
	return xxx_messageInfo_Invitation.Size(m)
}
func (m *Invitation) XXX_DiscardUnknown() {
	xxx_messageInfo_Invitation.DiscardUnknown(m)
}

var xxx_messageInfo_Invitation proto.InternalMessageInfo

func (m *Invitation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Invitation) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Invitation) GetTwitterScreenName() string {
	if m != nil {
		return m.TwitterScreenName
	}
	return ""
}

func (m *Invitation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Invitation) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Invitation) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type CreateConversationMessage struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Invitation           *Invitation   `protobuf:"bytes,2,opt,name=invitation,proto3" json:"invitation,omitempty"`
	InviteTwitterUser    bool          `protobuf:"varint,3,opt,name=inviteTwitterUser,proto3" json:"inviteTwitterUser,omitempty"`
	User                 *ConvUser     `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateConversationMessage) Reset()         { *m = CreateConversationMessage{} }
func (m *CreateConversationMessage) String() string { return proto.CompactTextString(m) }
func (*CreateConversationMessage) ProtoMessage()    {}
func (*CreateConversationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{1}
}

func (m *CreateConversationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationMessage.Unmarshal(m, b)
}
func (m *CreateConversationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationMessage.Marshal(b, m, deterministic)
}
func (m *CreateConversationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationMessage.Merge(m, src)
}
func (m *CreateConversationMessage) XXX_Size() int {
	return xxx_messageInfo_CreateConversationMessage.Size(m)
}
func (m *CreateConversationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationMessage proto.InternalMessageInfo

func (m *CreateConversationMessage) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *CreateConversationMessage) GetInvitation() *Invitation {
	if m != nil {
		return m.Invitation
	}
	return nil
}

func (m *CreateConversationMessage) GetInviteTwitterUser() bool {
	if m != nil {
		return m.InviteTwitterUser
	}
	return false
}

func (m *CreateConversationMessage) GetUser() *ConvUser {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateConversationResponse struct {
	Conversation         *Conversation `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{2}
}

func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (m *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(m, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetConversation() *Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

type GetInvitationsByUserIDMessage struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInvitationsByUserIDMessage) Reset()         { *m = GetInvitationsByUserIDMessage{} }
func (m *GetInvitationsByUserIDMessage) String() string { return proto.CompactTextString(m) }
func (*GetInvitationsByUserIDMessage) ProtoMessage()    {}
func (*GetInvitationsByUserIDMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{3}
}

func (m *GetInvitationsByUserIDMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitationsByUserIDMessage.Unmarshal(m, b)
}
func (m *GetInvitationsByUserIDMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitationsByUserIDMessage.Marshal(b, m, deterministic)
}
func (m *GetInvitationsByUserIDMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitationsByUserIDMessage.Merge(m, src)
}
func (m *GetInvitationsByUserIDMessage) XXX_Size() int {
	return xxx_messageInfo_GetInvitationsByUserIDMessage.Size(m)
}
func (m *GetInvitationsByUserIDMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitationsByUserIDMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitationsByUserIDMessage proto.InternalMessageInfo

func (m *GetInvitationsByUserIDMessage) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetInvitationsByUserIDMessage) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetInvitationsByUserIDResponse struct {
	InvitationList       []*Invitation `protobuf:"bytes,1,rep,name=invitationList,proto3" json:"invitationList,omitempty"`
	Page                 int32         `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32         `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32         `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInvitationsByUserIDResponse) Reset()         { *m = GetInvitationsByUserIDResponse{} }
func (m *GetInvitationsByUserIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetInvitationsByUserIDResponse) ProtoMessage()    {}
func (*GetInvitationsByUserIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{4}
}

func (m *GetInvitationsByUserIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitationsByUserIDResponse.Unmarshal(m, b)
}
func (m *GetInvitationsByUserIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitationsByUserIDResponse.Marshal(b, m, deterministic)
}
func (m *GetInvitationsByUserIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitationsByUserIDResponse.Merge(m, src)
}
func (m *GetInvitationsByUserIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetInvitationsByUserIDResponse.Size(m)
}
func (m *GetInvitationsByUserIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitationsByUserIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitationsByUserIDResponse proto.InternalMessageInfo

func (m *GetInvitationsByUserIDResponse) GetInvitationList() []*Invitation {
	if m != nil {
		return m.InvitationList
	}
	return nil
}

func (m *GetInvitationsByUserIDResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetInvitationsByUserIDResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetInvitationsByUserIDResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetInvitationByIDMessage struct {
	InvitationId         int64    `protobuf:"varint,1,opt,name=invitationId,proto3" json:"invitationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInvitationByIDMessage) Reset()         { *m = GetInvitationByIDMessage{} }
func (m *GetInvitationByIDMessage) String() string { return proto.CompactTextString(m) }
func (*GetInvitationByIDMessage) ProtoMessage()    {}
func (*GetInvitationByIDMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{5}
}

func (m *GetInvitationByIDMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitationByIDMessage.Unmarshal(m, b)
}
func (m *GetInvitationByIDMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitationByIDMessage.Marshal(b, m, deterministic)
}
func (m *GetInvitationByIDMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitationByIDMessage.Merge(m, src)
}
func (m *GetInvitationByIDMessage) XXX_Size() int {
	return xxx_messageInfo_GetInvitationByIDMessage.Size(m)
}
func (m *GetInvitationByIDMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitationByIDMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitationByIDMessage proto.InternalMessageInfo

func (m *GetInvitationByIDMessage) GetInvitationId() int64 {
	if m != nil {
		return m.InvitationId
	}
	return 0
}

type GetInvitationByIDResponse struct {
	Invitation           *Invitation `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetInvitationByIDResponse) Reset()         { *m = GetInvitationByIDResponse{} }
func (m *GetInvitationByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetInvitationByIDResponse) ProtoMessage()    {}
func (*GetInvitationByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{6}
}

func (m *GetInvitationByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvitationByIDResponse.Unmarshal(m, b)
}
func (m *GetInvitationByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvitationByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetInvitationByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvitationByIDResponse.Merge(m, src)
}
func (m *GetInvitationByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetInvitationByIDResponse.Size(m)
}
func (m *GetInvitationByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvitationByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvitationByIDResponse proto.InternalMessageInfo

func (m *GetInvitationByIDResponse) GetInvitation() *Invitation {
	if m != nil {
		return m.Invitation
	}
	return nil
}

type RejectInvitationMessage struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectInvitationMessage) Reset()         { *m = RejectInvitationMessage{} }
func (m *RejectInvitationMessage) String() string { return proto.CompactTextString(m) }
func (*RejectInvitationMessage) ProtoMessage()    {}
func (*RejectInvitationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{7}
}

func (m *RejectInvitationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectInvitationMessage.Unmarshal(m, b)
}
func (m *RejectInvitationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectInvitationMessage.Marshal(b, m, deterministic)
}
func (m *RejectInvitationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectInvitationMessage.Merge(m, src)
}
func (m *RejectInvitationMessage) XXX_Size() int {
	return xxx_messageInfo_RejectInvitationMessage.Size(m)
}
func (m *RejectInvitationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectInvitationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RejectInvitationMessage proto.InternalMessageInfo

func (m *RejectInvitationMessage) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type RejectInvitationResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectInvitationResponse) Reset()         { *m = RejectInvitationResponse{} }
func (m *RejectInvitationResponse) String() string { return proto.CompactTextString(m) }
func (*RejectInvitationResponse) ProtoMessage()    {}
func (*RejectInvitationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{8}
}

func (m *RejectInvitationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectInvitationResponse.Unmarshal(m, b)
}
func (m *RejectInvitationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectInvitationResponse.Marshal(b, m, deterministic)
}
func (m *RejectInvitationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectInvitationResponse.Merge(m, src)
}
func (m *RejectInvitationResponse) XXX_Size() int {
	return xxx_messageInfo_RejectInvitationResponse.Size(m)
}
func (m *RejectInvitationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectInvitationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RejectInvitationResponse proto.InternalMessageInfo

func (m *RejectInvitationResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type AcceptInvitationMessage struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptInvitationMessage) Reset()         { *m = AcceptInvitationMessage{} }
func (m *AcceptInvitationMessage) String() string { return proto.CompactTextString(m) }
func (*AcceptInvitationMessage) ProtoMessage()    {}
func (*AcceptInvitationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{9}
}

func (m *AcceptInvitationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptInvitationMessage.Unmarshal(m, b)
}
func (m *AcceptInvitationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptInvitationMessage.Marshal(b, m, deterministic)
}
func (m *AcceptInvitationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptInvitationMessage.Merge(m, src)
}
func (m *AcceptInvitationMessage) XXX_Size() int {
	return xxx_messageInfo_AcceptInvitationMessage.Size(m)
}
func (m *AcceptInvitationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptInvitationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptInvitationMessage proto.InternalMessageInfo

func (m *AcceptInvitationMessage) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type AcceptInvitationResponse struct {
	ConversationId       int64    `protobuf:"varint,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptInvitationResponse) Reset()         { *m = AcceptInvitationResponse{} }
func (m *AcceptInvitationResponse) String() string { return proto.CompactTextString(m) }
func (*AcceptInvitationResponse) ProtoMessage()    {}
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{10}
}

func (m *AcceptInvitationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptInvitationResponse.Unmarshal(m, b)
}
func (m *AcceptInvitationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptInvitationResponse.Marshal(b, m, deterministic)
}
func (m *AcceptInvitationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptInvitationResponse.Merge(m, src)
}
func (m *AcceptInvitationResponse) XXX_Size() int {
	return xxx_messageInfo_AcceptInvitationResponse.Size(m)
}
func (m *AcceptInvitationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptInvitationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptInvitationResponse proto.InternalMessageInfo

func (m *AcceptInvitationResponse) GetConversationId() int64 {
	if m != nil {
		return m.ConversationId
	}
	return 0
}

type LinkTwitterUserToConversationsRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TwitterScreenName    string   `protobuf:"bytes,2,opt,name=twitterScreenName,proto3" json:"twitterScreenName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkTwitterUserToConversationsRequest) Reset()         { *m = LinkTwitterUserToConversationsRequest{} }
func (m *LinkTwitterUserToConversationsRequest) String() string { return proto.CompactTextString(m) }
func (*LinkTwitterUserToConversationsRequest) ProtoMessage()    {}
func (*LinkTwitterUserToConversationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{11}
}

func (m *LinkTwitterUserToConversationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkTwitterUserToConversationsRequest.Unmarshal(m, b)
}
func (m *LinkTwitterUserToConversationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkTwitterUserToConversationsRequest.Marshal(b, m, deterministic)
}
func (m *LinkTwitterUserToConversationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkTwitterUserToConversationsRequest.Merge(m, src)
}
func (m *LinkTwitterUserToConversationsRequest) XXX_Size() int {
	return xxx_messageInfo_LinkTwitterUserToConversationsRequest.Size(m)
}
func (m *LinkTwitterUserToConversationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkTwitterUserToConversationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkTwitterUserToConversationsRequest proto.InternalMessageInfo

func (m *LinkTwitterUserToConversationsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LinkTwitterUserToConversationsRequest) GetTwitterScreenName() string {
	if m != nil {
		return m.TwitterScreenName
	}
	return ""
}

type LinkTwitterUserToConversationsResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkTwitterUserToConversationsResponse) Reset() {
	*m = LinkTwitterUserToConversationsResponse{}
}
func (m *LinkTwitterUserToConversationsResponse) String() string { return proto.CompactTextString(m) }
func (*LinkTwitterUserToConversationsResponse) ProtoMessage()    {}
func (*LinkTwitterUserToConversationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa06fe8a7d84bbc, []int{12}
}

func (m *LinkTwitterUserToConversationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkTwitterUserToConversationsResponse.Unmarshal(m, b)
}
func (m *LinkTwitterUserToConversationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkTwitterUserToConversationsResponse.Marshal(b, m, deterministic)
}
func (m *LinkTwitterUserToConversationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkTwitterUserToConversationsResponse.Merge(m, src)
}
func (m *LinkTwitterUserToConversationsResponse) XXX_Size() int {
	return xxx_messageInfo_LinkTwitterUserToConversationsResponse.Size(m)
}
func (m *LinkTwitterUserToConversationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkTwitterUserToConversationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkTwitterUserToConversationsResponse proto.InternalMessageInfo

func (m *LinkTwitterUserToConversationsResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*Invitation)(nil), "proto.Invitation")
	proto.RegisterType((*CreateConversationMessage)(nil), "proto.CreateConversationMessage")
	proto.RegisterType((*CreateConversationResponse)(nil), "proto.CreateConversationResponse")
	proto.RegisterType((*GetInvitationsByUserIDMessage)(nil), "proto.GetInvitationsByUserIDMessage")
	proto.RegisterType((*GetInvitationsByUserIDResponse)(nil), "proto.GetInvitationsByUserIDResponse")
	proto.RegisterType((*GetInvitationByIDMessage)(nil), "proto.GetInvitationByIDMessage")
	proto.RegisterType((*GetInvitationByIDResponse)(nil), "proto.GetInvitationByIDResponse")
	proto.RegisterType((*RejectInvitationMessage)(nil), "proto.RejectInvitationMessage")
	proto.RegisterType((*RejectInvitationResponse)(nil), "proto.RejectInvitationResponse")
	proto.RegisterType((*AcceptInvitationMessage)(nil), "proto.AcceptInvitationMessage")
	proto.RegisterType((*AcceptInvitationResponse)(nil), "proto.AcceptInvitationResponse")
	proto.RegisterType((*LinkTwitterUserToConversationsRequest)(nil), "proto.LinkTwitterUserToConversationsRequest")
	proto.RegisterType((*LinkTwitterUserToConversationsResponse)(nil), "proto.LinkTwitterUserToConversationsResponse")
}

func init() { proto.RegisterFile("proto/invitation.proto", fileDescriptor_afa06fe8a7d84bbc) }

var fileDescriptor_afa06fe8a7d84bbc = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdf, 0x6e, 0xd3, 0x3e,
	0x14, 0xfe, 0xb9, 0xff, 0x7e, 0xe3, 0x6c, 0x1a, 0xd4, 0x4c, 0x25, 0x8b, 0xc6, 0x16, 0x0c, 0x1b,
	0x15, 0xda, 0x1a, 0x51, 0x24, 0x10, 0x08, 0x21, 0xad, 0x43, 0x42, 0x95, 0xc6, 0x2e, 0xb2, 0xed,
	0x86, 0xbb, 0x2c, 0xb5, 0x8a, 0xd9, 0x1a, 0x97, 0xc4, 0x6d, 0x35, 0xa1, 0x09, 0x04, 0x17, 0x3c,
	0x00, 0x97, 0xbc, 0x01, 0x2f, 0xc2, 0x03, 0x70, 0xc7, 0x35, 0x0f, 0x82, 0xe2, 0xa4, 0x89, 0x9b,
	0x34, 0x5d, 0x81, 0xab, 0xd8, 0x3e, 0xc7, 0xe7, 0xfb, 0xfc, 0xf9, 0x7c, 0x6e, 0xa1, 0xd6, 0xf7,
	0xb8, 0xe0, 0x26, 0x73, 0x87, 0x4c, 0xd8, 0x82, 0x71, 0xb7, 0x21, 0x17, 0x70, 0x59, 0x7e, 0x74,
	0x2d, 0x0c, 0x3b, 0xdc, 0x1d, 0x52, 0xcf, 0x57, 0x12, 0xf4, 0xb5, 0x2e, 0xe7, 0xdd, 0x33, 0x6a,
	0xda, 0x7d, 0x66, 0xda, 0xae, 0xcb, 0xc3, 0xdd, 0x7e, 0x14, 0x7d, 0xd8, 0x65, 0xe2, 0xf5, 0xe0,
	0xa4, 0xe1, 0xf0, 0x9e, 0xd9, 0x1b, 0x31, 0x71, 0xca, 0x47, 0x66, 0x97, 0xef, 0xc8, 0xe0, 0xce,
	0xd0, 0x3e, 0x63, 0x1d, 0x5b, 0x70, 0xcf, 0x37, 0xe3, 0x61, 0xb8, 0x8f, 0x7c, 0x47, 0x00, 0xed,
	0x98, 0x0b, 0x5e, 0x86, 0x02, 0xeb, 0x68, 0xc8, 0x40, 0xf5, 0xa2, 0x55, 0x60, 0x1d, 0x5c, 0x83,
	0xca, 0xc0, 0xa7, 0x5e, 0xbb, 0xa3, 0x15, 0xe4, 0x5a, 0x34, 0xc3, 0xdb, 0x50, 0x15, 0x23, 0x26,
	0x04, 0xf5, 0x0e, 0x1d, 0x8f, 0x52, 0xf7, 0xc0, 0xee, 0x51, 0xad, 0x68, 0xa0, 0xfa, 0x15, 0x2b,
	0x1b, 0xc0, 0x18, 0x4a, 0x6e, 0x90, 0x50, 0x92, 0x09, 0x72, 0x1c, 0x54, 0xb6, 0x87, 0xb6, 0xb0,
	0x3d, 0xad, 0x2c, 0x57, 0xa3, 0x19, 0x7e, 0x04, 0x4b, 0xea, 0xe1, 0xb5, 0x8a, 0x81, 0xea, 0x8b,
	0xcd, 0xeb, 0x21, 0xdd, 0xc6, 0x9e, 0x12, 0xb2, 0x26, 0x12, 0xc9, 0x4f, 0x04, 0xab, 0x7b, 0x1e,
	0xb5, 0x05, 0x55, 0x93, 0x5e, 0x52, 0xdf, 0xb7, 0xbb, 0x34, 0x53, 0x16, 0xcd, 0x59, 0x16, 0xdf,
	0x07, 0x48, 0xee, 0x4a, 0xaa, 0xb0, 0xd8, 0xac, 0x46, 0xdb, 0x12, 0xe1, 0x2c, 0x25, 0x29, 0x10,
	0x47, 0xce, 0xe8, 0x51, 0xa8, 0xc4, 0xb1, 0x4f, 0x3d, 0x29, 0xce, 0x82, 0x95, 0x0d, 0xe0, 0xdb,
	0x50, 0x0a, 0x44, 0x95, 0xe2, 0x2c, 0x36, 0xaf, 0x2a, 0x8c, 0x82, 0xb0, 0x25, 0x83, 0xe4, 0x18,
	0xf4, 0xec, 0xd9, 0x2c, 0xea, 0xf7, 0xb9, 0xeb, 0xff, 0xfd, 0xe1, 0x48, 0x1b, 0x6e, 0xbe, 0xa0,
	0x22, 0x39, 0x86, 0xdf, 0x3a, 0x0f, 0x40, 0xdb, 0xcf, 0xc7, 0xb2, 0x61, 0x28, 0xf5, 0xed, 0x2e,
	0x95, 0x15, 0xcb, 0x96, 0x1c, 0xe3, 0x15, 0x28, 0x9f, 0xb1, 0x1e, 0x13, 0x52, 0x8c, 0xb2, 0x15,
	0x4e, 0xc8, 0x57, 0x04, 0xeb, 0xd3, 0x6b, 0xc5, 0x34, 0x1f, 0xc3, 0x72, 0xa2, 0xd2, 0x3e, 0xf3,
	0x85, 0x86, 0x8c, 0xe2, 0x74, 0x39, 0x53, 0x89, 0x31, 0x8f, 0xc2, 0x34, 0x1e, 0x45, 0x85, 0x47,
	0xb0, 0xea, 0xf0, 0x81, 0x2b, 0xa4, 0x9e, 0x65, 0x2b, 0x9c, 0x90, 0x67, 0xa0, 0x4d, 0x90, 0x6b,
	0x9d, 0x27, 0x67, 0x24, 0xb0, 0x94, 0xa0, 0xb5, 0xc7, 0xdd, 0x3f, 0xb1, 0x46, 0x0e, 0x60, 0x35,
	0xb3, 0x3f, 0x3e, 0xd7, 0x64, 0x8b, 0xa0, 0x39, 0x5a, 0x84, 0xec, 0xc2, 0x0d, 0x8b, 0xbe, 0xa1,
	0x8e, 0x52, 0x72, 0x4c, 0x67, 0x0b, 0x96, 0xd5, 0x3b, 0x8a, 0x09, 0xa5, 0x56, 0x49, 0x03, 0xb4,
	0x74, 0x89, 0x98, 0x11, 0x86, 0x52, 0x87, 0xbb, 0xe1, 0xb5, 0x2d, 0x58, 0x72, 0x1c, 0x40, 0xee,
	0x3a, 0x0e, 0xed, 0xff, 0x03, 0x64, 0x0b, 0xb4, 0x74, 0x89, 0x18, 0x72, 0xde, 0x1a, 0x3d, 0xd8,
	0xdc, 0x67, 0xee, 0xa9, 0xe2, 0x80, 0x23, 0xae, 0x76, 0xa8, 0x6f, 0xd1, 0xb7, 0x03, 0xea, 0x0b,
	0xe5, 0xe9, 0x41, 0x97, 0x3f, 0x3d, 0x85, 0x9c, 0xa7, 0x87, 0x3c, 0x85, 0xad, 0xcb, 0xe0, 0xf2,
	0x35, 0x6b, 0x7e, 0xab, 0x40, 0x35, 0x39, 0xeb, 0x21, 0xf5, 0x86, 0xcc, 0xa1, 0x78, 0x04, 0x38,
	0x6b, 0x46, 0x6c, 0x8c, 0xed, 0x96, 0xf7, 0x06, 0xe9, 0xb7, 0x72, 0x33, 0xc6, 0x24, 0xc8, 0xda,
	0xc7, 0x1f, 0xbf, 0xbe, 0x14, 0x6a, 0xa4, 0x2a, 0x9f, 0x79, 0x55, 0xba, 0x27, 0xe8, 0x1e, 0xfe,
	0x84, 0xa0, 0x36, 0xdd, 0x63, 0xf8, 0x4e, 0x54, 0x7b, 0xa6, 0x9d, 0xf5, 0xcd, 0x99, 0x59, 0x69,
	0x16, 0x78, 0x45, 0xb2, 0x08, 0x74, 0x57, 0x7e, 0xaf, 0xf0, 0x07, 0x04, 0xd5, 0x8c, 0x19, 0xf0,
	0xc6, 0xb4, 0xd2, 0x8a, 0xcd, 0x74, 0x23, 0x2f, 0x21, 0x86, 0xad, 0x4b, 0x58, 0x82, 0x0d, 0x09,
	0xdb, 0x57, 0x30, 0xcd, 0x77, 0xaa, 0x1b, 0x2f, 0xf0, 0x67, 0x04, 0xd7, 0xd2, 0xcd, 0x8f, 0xd7,
	0x23, 0x80, 0x1c, 0x63, 0xe9, 0x1b, 0x39, 0xf1, 0x18, 0xbf, 0x29, 0xf1, 0xb7, 0xc9, 0x5d, 0x89,
	0xaf, 0xa2, 0x4f, 0xf6, 0xf0, 0x85, 0xe9, 0xc9, 0x12, 0xc1, 0x95, 0x04, 0x4c, 0xd2, 0x9e, 0x88,
	0x99, 0xe4, 0xf8, 0x2d, 0x66, 0x92, 0x67, 0xa6, 0x3f, 0x60, 0x62, 0xcb, 0x12, 0x01, 0x93, 0xf7,
	0xb0, 0x3e, 0xbb, 0xd3, 0xf1, 0x76, 0x04, 0x3b, 0x97, 0xff, 0xf4, 0x9d, 0x39, 0xb3, 0x23, 0xca,
	0xff, 0xb5, 0xfe, 0x7f, 0x15, 0xfe, 0x87, 0x39, 0xa9, 0xc8, 0xcf, 0x83, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x2a, 0xeb, 0xd8, 0xeb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvitationServiceClient is the client API for InvitationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvitationServiceClient interface {
	CreateConversation(ctx context.Context, in *CreateConversationMessage, opts ...grpc.CallOption) (*CreateConversationResponse, error)
	GetInvitationsByUserID(ctx context.Context, in *GetInvitationsByUserIDMessage, opts ...grpc.CallOption) (*GetInvitationsByUserIDResponse, error)
	GetInvitationByID(ctx context.Context, in *GetInvitationByIDMessage, opts ...grpc.CallOption) (*GetInvitationByIDResponse, error)
	RejectInvitation(ctx context.Context, in *RejectInvitationMessage, opts ...grpc.CallOption) (*RejectInvitationResponse, error)
	AcceptInvitation(ctx context.Context, in *AcceptInvitationMessage, opts ...grpc.CallOption) (*AcceptInvitationResponse, error)
	LinkTwitterUserToConversations(ctx context.Context, in *LinkTwitterUserToConversationsRequest, opts ...grpc.CallOption) (*LinkTwitterUserToConversationsResponse, error)
}

type invitationServiceClient struct {
	cc *grpc.ClientConn
}

func NewInvitationServiceClient(cc *grpc.ClientConn) InvitationServiceClient {
	return &invitationServiceClient{cc}
}

func (c *invitationServiceClient) CreateConversation(ctx context.Context, in *CreateConversationMessage, opts ...grpc.CallOption) (*CreateConversationResponse, error) {
	out := new(CreateConversationResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/CreateConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) GetInvitationsByUserID(ctx context.Context, in *GetInvitationsByUserIDMessage, opts ...grpc.CallOption) (*GetInvitationsByUserIDResponse, error) {
	out := new(GetInvitationsByUserIDResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/GetInvitationsByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) GetInvitationByID(ctx context.Context, in *GetInvitationByIDMessage, opts ...grpc.CallOption) (*GetInvitationByIDResponse, error) {
	out := new(GetInvitationByIDResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/GetInvitationByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) RejectInvitation(ctx context.Context, in *RejectInvitationMessage, opts ...grpc.CallOption) (*RejectInvitationResponse, error) {
	out := new(RejectInvitationResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/RejectInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) AcceptInvitation(ctx context.Context, in *AcceptInvitationMessage, opts ...grpc.CallOption) (*AcceptInvitationResponse, error) {
	out := new(AcceptInvitationResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/AcceptInvitation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invitationServiceClient) LinkTwitterUserToConversations(ctx context.Context, in *LinkTwitterUserToConversationsRequest, opts ...grpc.CallOption) (*LinkTwitterUserToConversationsResponse, error) {
	out := new(LinkTwitterUserToConversationsResponse)
	err := c.cc.Invoke(ctx, "/proto.InvitationService/LinkTwitterUserToConversations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvitationServiceServer is the server API for InvitationService service.
type InvitationServiceServer interface {
	CreateConversation(context.Context, *CreateConversationMessage) (*CreateConversationResponse, error)
	GetInvitationsByUserID(context.Context, *GetInvitationsByUserIDMessage) (*GetInvitationsByUserIDResponse, error)
	GetInvitationByID(context.Context, *GetInvitationByIDMessage) (*GetInvitationByIDResponse, error)
	RejectInvitation(context.Context, *RejectInvitationMessage) (*RejectInvitationResponse, error)
	AcceptInvitation(context.Context, *AcceptInvitationMessage) (*AcceptInvitationResponse, error)
	LinkTwitterUserToConversations(context.Context, *LinkTwitterUserToConversationsRequest) (*LinkTwitterUserToConversationsResponse, error)
}

func RegisterInvitationServiceServer(s *grpc.Server, srv InvitationServiceServer) {
	s.RegisterService(&_InvitationService_serviceDesc, srv)
}

func _InvitationService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/CreateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).CreateConversation(ctx, req.(*CreateConversationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_GetInvitationsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitationsByUserIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).GetInvitationsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/GetInvitationsByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).GetInvitationsByUserID(ctx, req.(*GetInvitationsByUserIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_GetInvitationByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitationByIDMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).GetInvitationByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/GetInvitationByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).GetInvitationByID(ctx, req.(*GetInvitationByIDMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_RejectInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectInvitationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).RejectInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/RejectInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).RejectInvitation(ctx, req.(*RejectInvitationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_AcceptInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptInvitationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).AcceptInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/AcceptInvitation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).AcceptInvitation(ctx, req.(*AcceptInvitationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvitationService_LinkTwitterUserToConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTwitterUserToConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvitationServiceServer).LinkTwitterUserToConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InvitationService/LinkTwitterUserToConversations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvitationServiceServer).LinkTwitterUserToConversations(ctx, req.(*LinkTwitterUserToConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvitationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.InvitationService",
	HandlerType: (*InvitationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _InvitationService_CreateConversation_Handler,
		},
		{
			MethodName: "GetInvitationsByUserID",
			Handler:    _InvitationService_GetInvitationsByUserID_Handler,
		},
		{
			MethodName: "GetInvitationByID",
			Handler:    _InvitationService_GetInvitationByID_Handler,
		},
		{
			MethodName: "RejectInvitation",
			Handler:    _InvitationService_RejectInvitation_Handler,
		},
		{
			MethodName: "AcceptInvitation",
			Handler:    _InvitationService_AcceptInvitation_Handler,
		},
		{
			MethodName: "LinkTwitterUserToConversations",
			Handler:    _InvitationService_LinkTwitterUserToConversations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/invitation.proto",
}
