// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package discussproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string            `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string            `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	TwitterScreenName    string            `protobuf:"bytes,5,opt,name=twitterScreenName,proto3" json:"twitterScreenName,omitempty"`
	TwitterId            string            `protobuf:"bytes,6,opt,name=twitterId,proto3" json:"twitterId,omitempty"`
	TwitterVerified      bool              `protobuf:"varint,7,opt,name=twitterVerified,proto3" json:"twitterVerified,omitempty"`
	TimeZone             string            `protobuf:"bytes,8,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	IsTwitterAccount     bool              `protobuf:"varint,9,opt,name=isTwitterAccount,proto3" json:"isTwitterAccount,omitempty"`
	Profile              *Profile          `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	Education            []*Education      `protobuf:"bytes,11,rep,name=education,proto3" json:"education,omitempty"`
	WorkExperience       []*WorkExperience `protobuf:"bytes,12,rep,name=workExperience,proto3" json:"workExperience,omitempty"`
	TagLine              string            `protobuf:"bytes,13,opt,name=tagLine,proto3" json:"tagLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetTwitterScreenName() string {
	if m != nil {
		return m.TwitterScreenName
	}
	return ""
}

func (m *User) GetTwitterId() string {
	if m != nil {
		return m.TwitterId
	}
	return ""
}

func (m *User) GetTwitterVerified() bool {
	if m != nil {
		return m.TwitterVerified
	}
	return false
}

func (m *User) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *User) GetIsTwitterAccount() bool {
	if m != nil {
		return m.IsTwitterAccount
	}
	return false
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *User) GetEducation() []*Education {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *User) GetWorkExperience() []*WorkExperience {
	if m != nil {
		return m.WorkExperience
	}
	return nil
}

func (m *User) GetTagLine() string {
	if m != nil {
		return m.TagLine
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RefreshUserTokenRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshUserTokenRequest) Reset()         { *m = RefreshUserTokenRequest{} }
func (m *RefreshUserTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshUserTokenRequest) ProtoMessage()    {}
func (*RefreshUserTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RefreshUserTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshUserTokenRequest.Unmarshal(m, b)
}
func (m *RefreshUserTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshUserTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshUserTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshUserTokenRequest.Merge(m, src)
}
func (m *RefreshUserTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshUserTokenRequest.Size(m)
}
func (m *RefreshUserTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshUserTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshUserTokenRequest proto.InternalMessageInfo

func (m *RefreshUserTokenRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RefreshUserTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshUserTokenResponse) Reset()         { *m = RefreshUserTokenResponse{} }
func (m *RefreshUserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshUserTokenResponse) ProtoMessage()    {}
func (*RefreshUserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *RefreshUserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshUserTokenResponse.Unmarshal(m, b)
}
func (m *RefreshUserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshUserTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshUserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshUserTokenResponse.Merge(m, src)
}
func (m *RefreshUserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshUserTokenResponse.Size(m)
}
func (m *RefreshUserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshUserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshUserTokenResponse proto.InternalMessageInfo

func (m *RefreshUserTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateUserRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	RepeatedPassword     string   `protobuf:"bytes,2,opt,name=repeatedPassword,proto3" json:"repeatedPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRepeatedPassword() string {
	if m != nil {
		return m.RepeatedPassword
	}
	return ""
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	NewPasswordRepeat    string   `protobuf:"bytes,3,opt,name=newPasswordRepeat,proto3" json:"newPasswordRepeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPasswordRepeat() string {
	if m != nil {
		return m.NewPasswordRepeat
	}
	return ""
}

type ChangePasswordResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ChangePasswordFromTempRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	TempPassword         string   `protobuf:"bytes,2,opt,name=tempPassword,proto3" json:"tempPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	NewPasswordRepeat    string   `protobuf:"bytes,4,opt,name=newPasswordRepeat,proto3" json:"newPasswordRepeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordFromTempRequest) Reset()         { *m = ChangePasswordFromTempRequest{} }
func (m *ChangePasswordFromTempRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordFromTempRequest) ProtoMessage()    {}
func (*ChangePasswordFromTempRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *ChangePasswordFromTempRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordFromTempRequest.Unmarshal(m, b)
}
func (m *ChangePasswordFromTempRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordFromTempRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordFromTempRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordFromTempRequest.Merge(m, src)
}
func (m *ChangePasswordFromTempRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordFromTempRequest.Size(m)
}
func (m *ChangePasswordFromTempRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordFromTempRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordFromTempRequest proto.InternalMessageInfo

func (m *ChangePasswordFromTempRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangePasswordFromTempRequest) GetTempPassword() string {
	if m != nil {
		return m.TempPassword
	}
	return ""
}

func (m *ChangePasswordFromTempRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordFromTempRequest) GetNewPasswordRepeat() string {
	if m != nil {
		return m.NewPasswordRepeat
	}
	return ""
}

type ChangePasswordFromTempResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordFromTempResponse) Reset()         { *m = ChangePasswordFromTempResponse{} }
func (m *ChangePasswordFromTempResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordFromTempResponse) ProtoMessage()    {}
func (*ChangePasswordFromTempResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ChangePasswordFromTempResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordFromTempResponse.Unmarshal(m, b)
}
func (m *ChangePasswordFromTempResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordFromTempResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordFromTempResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordFromTempResponse.Merge(m, src)
}
func (m *ChangePasswordFromTempResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordFromTempResponse.Size(m)
}
func (m *ChangePasswordFromTempResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordFromTempResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordFromTempResponse proto.InternalMessageInfo

func (m *ChangePasswordFromTempResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChangePasswordFromTempResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RequestPasswordResetRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPasswordResetRequest) Reset()         { *m = RequestPasswordResetRequest{} }
func (m *RequestPasswordResetRequest) String() string { return proto.CompactTextString(m) }
func (*RequestPasswordResetRequest) ProtoMessage()    {}
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *RequestPasswordResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPasswordResetRequest.Unmarshal(m, b)
}
func (m *RequestPasswordResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPasswordResetRequest.Marshal(b, m, deterministic)
}
func (m *RequestPasswordResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPasswordResetRequest.Merge(m, src)
}
func (m *RequestPasswordResetRequest) XXX_Size() int {
	return xxx_messageInfo_RequestPasswordResetRequest.Size(m)
}
func (m *RequestPasswordResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPasswordResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPasswordResetRequest proto.InternalMessageInfo

func (m *RequestPasswordResetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RequestPasswordResetResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPasswordResetResponse) Reset()         { *m = RequestPasswordResetResponse{} }
func (m *RequestPasswordResetResponse) String() string { return proto.CompactTextString(m) }
func (*RequestPasswordResetResponse) ProtoMessage()    {}
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *RequestPasswordResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPasswordResetResponse.Unmarshal(m, b)
}
func (m *RequestPasswordResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPasswordResetResponse.Marshal(b, m, deterministic)
}
func (m *RequestPasswordResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPasswordResetResponse.Merge(m, src)
}
func (m *RequestPasswordResetResponse) XXX_Size() int {
	return xxx_messageInfo_RequestPasswordResetResponse.Size(m)
}
func (m *RequestPasswordResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPasswordResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPasswordResetResponse proto.InternalMessageInfo

func (m *RequestPasswordResetResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *RequestPasswordResetResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetUsersRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	SearchTerm           string   `protobuf:"bytes,3,opt,name=searchTerm,proto3" json:"searchTerm,omitempty"`
	Expand               string   `protobuf:"bytes,4,opt,name=expand,proto3" json:"expand,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUsersRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUsersRequest) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

func (m *GetUsersRequest) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

func (m *GetUsersRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetUsersRequest) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

type GetUsersResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	SortByDirection      string   `protobuf:"bytes,6,opt,name=sortByDirection,proto3" json:"sortByDirection,omitempty"`
	SearchTerm           string   `protobuf:"bytes,8,opt,name=searchTerm,proto3" json:"searchTerm,omitempty"`
	Expand               string   `protobuf:"bytes,9,opt,name=expand,proto3" json:"expand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUsersResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUsersResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetUsersResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUsersResponse) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *GetUsersResponse) GetSortByDirection() string {
	if m != nil {
		return m.SortByDirection
	}
	return ""
}

func (m *GetUsersResponse) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

func (m *GetUsersResponse) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

type GetByIdsRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Expand               string   `protobuf:"bytes,2,opt,name=expand,proto3" json:"expand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdsRequest) Reset()         { *m = GetByIdsRequest{} }
func (m *GetByIdsRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdsRequest) ProtoMessage()    {}
func (*GetByIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *GetByIdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdsRequest.Unmarshal(m, b)
}
func (m *GetByIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdsRequest.Marshal(b, m, deterministic)
}
func (m *GetByIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdsRequest.Merge(m, src)
}
func (m *GetByIdsRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdsRequest.Size(m)
}
func (m *GetByIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdsRequest proto.InternalMessageInfo

func (m *GetByIdsRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetByIdsRequest) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

type GetByIdsResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdsResponse) Reset()         { *m = GetByIdsResponse{} }
func (m *GetByIdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetByIdsResponse) ProtoMessage()    {}
func (*GetByIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *GetByIdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdsResponse.Unmarshal(m, b)
}
func (m *GetByIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdsResponse.Marshal(b, m, deterministic)
}
func (m *GetByIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdsResponse.Merge(m, src)
}
func (m *GetByIdsResponse) XXX_Size() int {
	return xxx_messageInfo_GetByIdsResponse.Size(m)
}
func (m *GetByIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdsResponse proto.InternalMessageInfo

func (m *GetByIdsResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserByIdRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Expand               string   `protobuf:"bytes,2,opt,name=expand,proto3" json:"expand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdRequest) Reset()         { *m = GetUserByIdRequest{} }
func (m *GetUserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdRequest) ProtoMessage()    {}
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *GetUserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdRequest.Unmarshal(m, b)
}
func (m *GetUserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdRequest.Merge(m, src)
}
func (m *GetUserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdRequest.Size(m)
}
func (m *GetUserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdRequest proto.InternalMessageInfo

func (m *GetUserByIdRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserByIdRequest) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

type GetUserByIdResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdResponse) Reset()         { *m = GetUserByIdResponse{} }
func (m *GetUserByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResponse) ProtoMessage()    {}
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{18}
}

func (m *GetUserByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResponse.Unmarshal(m, b)
}
func (m *GetUserByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResponse.Merge(m, src)
}
func (m *GetUserByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResponse.Size(m)
}
func (m *GetUserByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResponse proto.InternalMessageInfo

func (m *GetUserByIdResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserMeRequest struct {
	Expand               string   `protobuf:"bytes,1,opt,name=expand,proto3" json:"expand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserMeRequest) Reset()         { *m = GetUserMeRequest{} }
func (m *GetUserMeRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserMeRequest) ProtoMessage()    {}
func (*GetUserMeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{19}
}

func (m *GetUserMeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserMeRequest.Unmarshal(m, b)
}
func (m *GetUserMeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserMeRequest.Marshal(b, m, deterministic)
}
func (m *GetUserMeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserMeRequest.Merge(m, src)
}
func (m *GetUserMeRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserMeRequest.Size(m)
}
func (m *GetUserMeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserMeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserMeRequest proto.InternalMessageInfo

func (m *GetUserMeRequest) GetExpand() string {
	if m != nil {
		return m.Expand
	}
	return ""
}

type GetUserMeResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserMeResponse) Reset()         { *m = GetUserMeResponse{} }
func (m *GetUserMeResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserMeResponse) ProtoMessage()    {}
func (*GetUserMeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{20}
}

func (m *GetUserMeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserMeResponse.Unmarshal(m, b)
}
func (m *GetUserMeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserMeResponse.Marshal(b, m, deterministic)
}
func (m *GetUserMeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserMeResponse.Merge(m, src)
}
func (m *GetUserMeResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserMeResponse.Size(m)
}
func (m *GetUserMeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserMeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserMeResponse proto.InternalMessageInfo

func (m *GetUserMeResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{21}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{22}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{23}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

type DeleteUserResponse struct {
	UserDeleted          bool     `protobuf:"varint,1,opt,name=userDeleted,proto3" json:"userDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{24}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetUserDeleted() bool {
	if m != nil {
		return m.UserDeleted
	}
	return false
}

type GetUserByTwitterScreenNameRequest struct {
	Screenname           string   `protobuf:"bytes,1,opt,name=screenname,proto3" json:"screenname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByTwitterScreenNameRequest) Reset()         { *m = GetUserByTwitterScreenNameRequest{} }
func (m *GetUserByTwitterScreenNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByTwitterScreenNameRequest) ProtoMessage()    {}
func (*GetUserByTwitterScreenNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{25}
}

func (m *GetUserByTwitterScreenNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByTwitterScreenNameRequest.Unmarshal(m, b)
}
func (m *GetUserByTwitterScreenNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByTwitterScreenNameRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByTwitterScreenNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByTwitterScreenNameRequest.Merge(m, src)
}
func (m *GetUserByTwitterScreenNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByTwitterScreenNameRequest.Size(m)
}
func (m *GetUserByTwitterScreenNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByTwitterScreenNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByTwitterScreenNameRequest proto.InternalMessageInfo

func (m *GetUserByTwitterScreenNameRequest) GetScreenname() string {
	if m != nil {
		return m.Screenname
	}
	return ""
}

type GetUserByTwitterScreenNameResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByTwitterScreenNameResponse) Reset()         { *m = GetUserByTwitterScreenNameResponse{} }
func (m *GetUserByTwitterScreenNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByTwitterScreenNameResponse) ProtoMessage()    {}
func (*GetUserByTwitterScreenNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{26}
}

func (m *GetUserByTwitterScreenNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByTwitterScreenNameResponse.Unmarshal(m, b)
}
func (m *GetUserByTwitterScreenNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByTwitterScreenNameResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByTwitterScreenNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByTwitterScreenNameResponse.Merge(m, src)
}
func (m *GetUserByTwitterScreenNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByTwitterScreenNameResponse.Size(m)
}
func (m *GetUserByTwitterScreenNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByTwitterScreenNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByTwitterScreenNameResponse proto.InternalMessageInfo

func (m *GetUserByTwitterScreenNameResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LinkTwitterRequest struct {
	OauthToken           string   `protobuf:"bytes,1,opt,name=oauthToken,proto3" json:"oauthToken,omitempty"`
	OauthVerifier        string   `protobuf:"bytes,2,opt,name=oauthVerifier,proto3" json:"oauthVerifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkTwitterRequest) Reset()         { *m = LinkTwitterRequest{} }
func (m *LinkTwitterRequest) String() string { return proto.CompactTextString(m) }
func (*LinkTwitterRequest) ProtoMessage()    {}
func (*LinkTwitterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{27}
}

func (m *LinkTwitterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkTwitterRequest.Unmarshal(m, b)
}
func (m *LinkTwitterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkTwitterRequest.Marshal(b, m, deterministic)
}
func (m *LinkTwitterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkTwitterRequest.Merge(m, src)
}
func (m *LinkTwitterRequest) XXX_Size() int {
	return xxx_messageInfo_LinkTwitterRequest.Size(m)
}
func (m *LinkTwitterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkTwitterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkTwitterRequest proto.InternalMessageInfo

func (m *LinkTwitterRequest) GetOauthToken() string {
	if m != nil {
		return m.OauthToken
	}
	return ""
}

func (m *LinkTwitterRequest) GetOauthVerifier() string {
	if m != nil {
		return m.OauthVerifier
	}
	return ""
}

type LinkTwitterResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkTwitterResponse) Reset()         { *m = LinkTwitterResponse{} }
func (m *LinkTwitterResponse) String() string { return proto.CompactTextString(m) }
func (*LinkTwitterResponse) ProtoMessage()    {}
func (*LinkTwitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{28}
}

func (m *LinkTwitterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkTwitterResponse.Unmarshal(m, b)
}
func (m *LinkTwitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkTwitterResponse.Marshal(b, m, deterministic)
}
func (m *LinkTwitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkTwitterResponse.Merge(m, src)
}
func (m *LinkTwitterResponse) XXX_Size() int {
	return xxx_messageInfo_LinkTwitterResponse.Size(m)
}
func (m *LinkTwitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkTwitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkTwitterResponse proto.InternalMessageInfo

func (m *LinkTwitterResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UnLinkTwitterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnLinkTwitterRequest) Reset()         { *m = UnLinkTwitterRequest{} }
func (m *UnLinkTwitterRequest) String() string { return proto.CompactTextString(m) }
func (*UnLinkTwitterRequest) ProtoMessage()    {}
func (*UnLinkTwitterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{29}
}

func (m *UnLinkTwitterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnLinkTwitterRequest.Unmarshal(m, b)
}
func (m *UnLinkTwitterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnLinkTwitterRequest.Marshal(b, m, deterministic)
}
func (m *UnLinkTwitterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnLinkTwitterRequest.Merge(m, src)
}
func (m *UnLinkTwitterRequest) XXX_Size() int {
	return xxx_messageInfo_UnLinkTwitterRequest.Size(m)
}
func (m *UnLinkTwitterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnLinkTwitterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnLinkTwitterRequest proto.InternalMessageInfo

type UnLinkTwitterResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnLinkTwitterResponse) Reset()         { *m = UnLinkTwitterResponse{} }
func (m *UnLinkTwitterResponse) String() string { return proto.CompactTextString(m) }
func (*UnLinkTwitterResponse) ProtoMessage()    {}
func (*UnLinkTwitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{30}
}

func (m *UnLinkTwitterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnLinkTwitterResponse.Unmarshal(m, b)
}
func (m *UnLinkTwitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnLinkTwitterResponse.Marshal(b, m, deterministic)
}
func (m *UnLinkTwitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnLinkTwitterResponse.Merge(m, src)
}
func (m *UnLinkTwitterResponse) XXX_Size() int {
	return xxx_messageInfo_UnLinkTwitterResponse.Size(m)
}
func (m *UnLinkTwitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnLinkTwitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnLinkTwitterResponse proto.InternalMessageInfo

func (m *UnLinkTwitterResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetTwitterUserByScreenNameRequest struct {
	SearchTerm           string   `protobuf:"bytes,1,opt,name=searchTerm,proto3" json:"searchTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTwitterUserByScreenNameRequest) Reset()         { *m = GetTwitterUserByScreenNameRequest{} }
func (m *GetTwitterUserByScreenNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetTwitterUserByScreenNameRequest) ProtoMessage()    {}
func (*GetTwitterUserByScreenNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{31}
}

func (m *GetTwitterUserByScreenNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTwitterUserByScreenNameRequest.Unmarshal(m, b)
}
func (m *GetTwitterUserByScreenNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTwitterUserByScreenNameRequest.Marshal(b, m, deterministic)
}
func (m *GetTwitterUserByScreenNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTwitterUserByScreenNameRequest.Merge(m, src)
}
func (m *GetTwitterUserByScreenNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetTwitterUserByScreenNameRequest.Size(m)
}
func (m *GetTwitterUserByScreenNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTwitterUserByScreenNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTwitterUserByScreenNameRequest proto.InternalMessageInfo

func (m *GetTwitterUserByScreenNameRequest) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

type GetTwitterUserByScreenNameResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTwitterUserByScreenNameResponse) Reset()         { *m = GetTwitterUserByScreenNameResponse{} }
func (m *GetTwitterUserByScreenNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetTwitterUserByScreenNameResponse) ProtoMessage()    {}
func (*GetTwitterUserByScreenNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{32}
}

func (m *GetTwitterUserByScreenNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTwitterUserByScreenNameResponse.Unmarshal(m, b)
}
func (m *GetTwitterUserByScreenNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTwitterUserByScreenNameResponse.Marshal(b, m, deterministic)
}
func (m *GetTwitterUserByScreenNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTwitterUserByScreenNameResponse.Merge(m, src)
}
func (m *GetTwitterUserByScreenNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetTwitterUserByScreenNameResponse.Size(m)
}
func (m *GetTwitterUserByScreenNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTwitterUserByScreenNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTwitterUserByScreenNameResponse proto.InternalMessageInfo

func (m *GetTwitterUserByScreenNameResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetProfileImageUploadURLRequest struct {
	ContentType          string   `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileImageUploadURLRequest) Reset()         { *m = GetProfileImageUploadURLRequest{} }
func (m *GetProfileImageUploadURLRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileImageUploadURLRequest) ProtoMessage()    {}
func (*GetProfileImageUploadURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{33}
}

func (m *GetProfileImageUploadURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileImageUploadURLRequest.Unmarshal(m, b)
}
func (m *GetProfileImageUploadURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileImageUploadURLRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileImageUploadURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileImageUploadURLRequest.Merge(m, src)
}
func (m *GetProfileImageUploadURLRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileImageUploadURLRequest.Size(m)
}
func (m *GetProfileImageUploadURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileImageUploadURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileImageUploadURLRequest proto.InternalMessageInfo

func (m *GetProfileImageUploadURLRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

type GetProfileImageUploadURLResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileImageUploadURLResponse) Reset()         { *m = GetProfileImageUploadURLResponse{} }
func (m *GetProfileImageUploadURLResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileImageUploadURLResponse) ProtoMessage()    {}
func (*GetProfileImageUploadURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{34}
}

func (m *GetProfileImageUploadURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileImageUploadURLResponse.Unmarshal(m, b)
}
func (m *GetProfileImageUploadURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileImageUploadURLResponse.Marshal(b, m, deterministic)
}
func (m *GetProfileImageUploadURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileImageUploadURLResponse.Merge(m, src)
}
func (m *GetProfileImageUploadURLResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileImageUploadURLResponse.Size(m)
}
func (m *GetProfileImageUploadURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileImageUploadURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileImageUploadURLResponse proto.InternalMessageInfo

func (m *GetProfileImageUploadURLResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "discussproto.User")
	proto.RegisterType((*LoginRequest)(nil), "discussproto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "discussproto.LoginResponse")
	proto.RegisterType((*RefreshUserTokenRequest)(nil), "discussproto.RefreshUserTokenRequest")
	proto.RegisterType((*RefreshUserTokenResponse)(nil), "discussproto.RefreshUserTokenResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "discussproto.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "discussproto.CreateUserResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "discussproto.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "discussproto.ChangePasswordResponse")
	proto.RegisterType((*ChangePasswordFromTempRequest)(nil), "discussproto.ChangePasswordFromTempRequest")
	proto.RegisterType((*ChangePasswordFromTempResponse)(nil), "discussproto.ChangePasswordFromTempResponse")
	proto.RegisterType((*RequestPasswordResetRequest)(nil), "discussproto.RequestPasswordResetRequest")
	proto.RegisterType((*RequestPasswordResetResponse)(nil), "discussproto.RequestPasswordResetResponse")
	proto.RegisterType((*GetUsersRequest)(nil), "discussproto.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "discussproto.GetUsersResponse")
	proto.RegisterType((*GetByIdsRequest)(nil), "discussproto.GetByIdsRequest")
	proto.RegisterType((*GetByIdsResponse)(nil), "discussproto.GetByIdsResponse")
	proto.RegisterType((*GetUserByIdRequest)(nil), "discussproto.GetUserByIdRequest")
	proto.RegisterType((*GetUserByIdResponse)(nil), "discussproto.GetUserByIdResponse")
	proto.RegisterType((*GetUserMeRequest)(nil), "discussproto.GetUserMeRequest")
	proto.RegisterType((*GetUserMeResponse)(nil), "discussproto.GetUserMeResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "discussproto.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "discussproto.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "discussproto.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "discussproto.DeleteUserResponse")
	proto.RegisterType((*GetUserByTwitterScreenNameRequest)(nil), "discussproto.GetUserByTwitterScreenNameRequest")
	proto.RegisterType((*GetUserByTwitterScreenNameResponse)(nil), "discussproto.GetUserByTwitterScreenNameResponse")
	proto.RegisterType((*LinkTwitterRequest)(nil), "discussproto.LinkTwitterRequest")
	proto.RegisterType((*LinkTwitterResponse)(nil), "discussproto.LinkTwitterResponse")
	proto.RegisterType((*UnLinkTwitterRequest)(nil), "discussproto.UnLinkTwitterRequest")
	proto.RegisterType((*UnLinkTwitterResponse)(nil), "discussproto.UnLinkTwitterResponse")
	proto.RegisterType((*GetTwitterUserByScreenNameRequest)(nil), "discussproto.GetTwitterUserByScreenNameRequest")
	proto.RegisterType((*GetTwitterUserByScreenNameResponse)(nil), "discussproto.GetTwitterUserByScreenNameResponse")
	proto.RegisterType((*GetProfileImageUploadURLRequest)(nil), "discussproto.GetProfileImageUploadURLRequest")
	proto.RegisterType((*GetProfileImageUploadURLResponse)(nil), "discussproto.GetProfileImageUploadURLResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 1610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x4e, 0x1b, 0xc7,
	0x17, 0xff, 0x2f, 0xc6, 0x04, 0x1f, 0x03, 0xc1, 0x83, 0x21, 0xfb, 0x5f, 0x08, 0x98, 0x21, 0x4d,
	0x1c, 0x12, 0xe3, 0xc4, 0x4d, 0x73, 0xd1, 0xa4, 0xaa, 0x4a, 0x48, 0x23, 0x24, 0x52, 0x45, 0x1b,
	0xe8, 0x47, 0x2e, 0x22, 0x2d, 0xde, 0xc1, 0x8c, 0xb0, 0x77, 0xb7, 0xbb, 0xe3, 0x10, 0x14, 0xe5,
	0xa2, 0x55, 0xdf, 0xa0, 0xb7, 0xbd, 0xa9, 0x54, 0xf5, 0x01, 0x2a, 0xf5, 0x21, 0x7a, 0xdd, 0xfb,
	0x56, 0xaa, 0xfa, 0x08, 0x7d, 0x80, 0x6a, 0x66, 0x67, 0xd7, 0xb3, 0xeb, 0x5d, 0x83, 0xd5, 0x5c,
	0xb1, 0x73, 0x3e, 0x7f, 0xe7, 0x63, 0xe6, 0x1c, 0x0c, 0xd0, 0x0f, 0x88, 0xbf, 0xe5, 0xf9, 0x2e,
	0x73, 0xd1, 0x8c, 0x4d, 0x83, 0x76, 0x3f, 0x08, 0xc4, 0xc9, 0x98, 0xf5, 0x7c, 0xf7, 0x88, 0x76,
	0x49, 0xc8, 0x34, 0x2e, 0x13, 0xbb, 0xdf, 0xb6, 0x18, 0x75, 0x1d, 0x49, 0xa8, 0x9e, 0xba, 0xfe,
	0x09, 0x79, 0xed, 0x11, 0x9f, 0x12, 0xa7, 0x1d, 0x89, 0xad, 0x74, 0x5c, 0xb7, 0xd3, 0x25, 0x4d,
	0xcb, 0xa3, 0x4d, 0xcb, 0x71, 0x5c, 0x26, 0x54, 0x02, 0xc9, 0xbd, 0xdf, 0xa1, 0xec, 0xb8, 0x7f,
	0xb8, 0xd5, 0x76, 0x7b, 0xcd, 0xde, 0x29, 0x65, 0x27, 0xee, 0x69, 0xb3, 0xe3, 0x36, 0x04, 0xb3,
	0xf1, 0xca, 0xea, 0x52, 0xdb, 0x62, 0xae, 0x1f, 0x34, 0xe3, 0xcf, 0x50, 0x0f, 0xff, 0x51, 0x80,
	0xc9, 0x83, 0x80, 0xf8, 0x68, 0x0e, 0x26, 0xa8, 0xad, 0x6b, 0x35, 0xad, 0x5e, 0x30, 0x27, 0xa8,
	0x8d, 0x10, 0x4c, 0x3a, 0x56, 0x8f, 0xe8, 0x13, 0x35, 0xad, 0x5e, 0x32, 0xc5, 0x37, 0xaa, 0x42,
	0x91, 0xf4, 0x2c, 0xda, 0xd5, 0x0b, 0x82, 0x18, 0x1e, 0xd0, 0x12, 0x4c, 0x59, 0xaf, 0x2c, 0x66,
	0xf9, 0xfa, 0xa4, 0x20, 0xcb, 0x13, 0xba, 0x0d, 0x15, 0x76, 0x4a, 0x19, 0x23, 0xfe, 0xf3, 0xb6,
	0x4f, 0x88, 0xf3, 0x19, 0x37, 0x57, 0x14, 0x22, 0xc3, 0x0c, 0xb4, 0x02, 0x25, 0x49, 0xdc, 0xb5,
	0xf5, 0x29, 0x21, 0x35, 0x20, 0xa0, 0x3a, 0x5c, 0x96, 0x87, 0xcf, 0x89, 0x4f, 0x8f, 0x28, 0xb1,
	0xf5, 0x4b, 0x35, 0xad, 0x3e, 0x6d, 0xa6, 0xc9, 0xc8, 0x80, 0x69, 0x46, 0x7b, 0xe4, 0x85, 0xeb,
	0x10, 0x7d, 0x5a, 0x98, 0x89, 0xcf, 0x68, 0x13, 0xe6, 0x69, 0xb0, 0x1f, 0x2a, 0x7c, 0xd2, 0x6e,
	0xbb, 0x7d, 0x87, 0xe9, 0x25, 0x61, 0x66, 0x88, 0x8e, 0x9a, 0x70, 0x49, 0x96, 0x49, 0x87, 0x9a,
	0x56, 0x2f, 0xb7, 0x16, 0xb7, 0xd4, 0x22, 0x6e, 0x3d, 0x0b, 0x99, 0x66, 0x24, 0x85, 0x3e, 0x80,
	0x52, 0x5c, 0x48, 0xbd, 0x5c, 0x2b, 0xd4, 0xcb, 0xad, 0x2b, 0x49, 0x95, 0xc7, 0x11, 0xdb, 0x1c,
	0x48, 0xa2, 0x1d, 0x98, 0xe3, 0xe5, 0x7e, 0x1c, 0x97, 0x5b, 0x9f, 0x11, 0xba, 0x2b, 0x49, 0xdd,
	0x2f, 0x12, 0x32, 0x66, 0x4a, 0x07, 0xe9, 0x70, 0x89, 0x59, 0x9d, 0x3d, 0xea, 0x10, 0x7d, 0x56,
	0x04, 0x1d, 0x1d, 0xf1, 0x33, 0x98, 0xd9, 0x73, 0x3b, 0xd4, 0x31, 0xc9, 0xd7, 0x7d, 0x12, 0x30,
	0xb4, 0x12, 0xd5, 0x90, 0x97, 0xba, 0xb4, 0x3d, 0xf5, 0xd7, 0x9f, 0x6b, 0x13, 0x5f, 0x6a, 0x51,
	0x2d, 0x31, 0x4c, 0x7b, 0x56, 0x10, 0x9c, 0xba, 0xbe, 0x1d, 0x56, 0x3e, 0x16, 0x88, 0xe9, 0xf8,
	0x29, 0xcc, 0x4a, 0x8b, 0x81, 0xe7, 0x3a, 0x01, 0x41, 0xd7, 0x61, 0x92, 0xf7, 0xba, 0xb0, 0x58,
	0x6e, 0xa1, 0x24, 0x70, 0xde, 0x5c, 0xa6, 0xe0, 0xf3, 0xf6, 0x61, 0xee, 0x09, 0x71, 0x64, 0x4f,
	0x85, 0x07, 0x7c, 0x17, 0xae, 0x98, 0xe4, 0xc8, 0x27, 0xc1, 0x31, 0x17, 0xdd, 0xe7, 0xb4, 0x08,
	0xeb, 0x12, 0x4c, 0x71, 0xc5, 0xdd, 0xa8, 0x2f, 0xe5, 0x09, 0xdf, 0x01, 0x7d, 0x58, 0x45, 0x82,
	0x89, 0x9d, 0x68, 0xaa, 0x93, 0x13, 0xa8, 0x3c, 0xf2, 0x89, 0xc5, 0x88, 0x80, 0x23, 0xcd, 0xab,
	0xc1, 0x6a, 0xd9, 0xc1, 0xa2, 0x16, 0xcc, 0xfb, 0xc4, 0xe3, 0x9a, 0xf6, 0xb3, 0xec, 0xc4, 0x0c,
	0xf1, 0xb1, 0x09, 0x48, 0x75, 0xf6, 0x4e, 0xb2, 0xf4, 0xa3, 0x06, 0x8b, 0x8f, 0x8e, 0x2d, 0xa7,
	0x43, 0x22, 0x37, 0x51, 0x14, 0x75, 0x28, 0xbb, 0xdd, 0x01, 0xb8, 0x64, 0x20, 0x2a, 0x8b, 0x4b,
	0x3a, 0xe4, 0x34, 0x27, 0x0c, 0x95, 0x85, 0xee, 0x41, 0x45, 0x39, 0x9a, 0x22, 0xc0, 0xf0, 0xd2,
	0xc7, 0xf2, 0xc3, 0x02, 0xf8, 0x0e, 0x2c, 0xa5, 0x21, 0xca, 0xd8, 0x97, 0x60, 0x2a, 0x60, 0x16,
	0xeb, 0x07, 0x02, 0xde, 0xb4, 0x29, 0x4f, 0xf8, 0x37, 0x0d, 0xae, 0x26, 0x55, 0x3e, 0xf5, 0xdd,
	0xde, 0x3e, 0xe9, 0x79, 0x17, 0x6b, 0xd7, 0x4d, 0x98, 0x61, 0xa4, 0xe7, 0xe5, 0x84, 0x94, 0xe0,
	0xa5, 0xa3, 0x2f, 0x8c, 0x19, 0xfd, 0xe4, 0x79, 0xd1, 0xbf, 0x84, 0xd5, 0xbc, 0x50, 0xde, 0x49,
	0x07, 0x3c, 0x80, 0x65, 0x99, 0x14, 0x25, 0xbd, 0x84, 0x5d, 0x28, 0x51, 0x78, 0x0f, 0x56, 0xb2,
	0x95, 0x47, 0x17, 0x28, 0x07, 0xca, 0xaf, 0x1a, 0x5c, 0x7e, 0x42, 0x18, 0x87, 0x1c, 0x44, 0xfe,
	0xab, 0x50, 0xec, 0xd2, 0x1e, 0x65, 0xc2, 0x40, 0xd1, 0x0c, 0x0f, 0x7c, 0x8a, 0x78, 0x56, 0x27,
	0x9c, 0x22, 0x45, 0x53, 0x7c, 0xa3, 0x55, 0x80, 0x80, 0x58, 0x7e, 0xfb, 0x78, 0x9f, 0xf8, 0x3d,
	0x39, 0x4a, 0x14, 0x0a, 0xc7, 0x42, 0x5e, 0x7b, 0x96, 0x63, 0x47, 0xf3, 0x24, 0x3c, 0x09, 0x8c,
	0xae, 0xcf, 0xb6, 0xcf, 0xe4, 0x10, 0x91, 0x27, 0x3e, 0x1b, 0xc2, 0xaf, 0x1d, 0xea, 0x93, 0xb6,
	0x78, 0x7e, 0xc3, 0xf9, 0x91, 0x26, 0xe3, 0x7f, 0x34, 0x98, 0x1f, 0xe0, 0x1e, 0x54, 0xc5, 0xb6,
	0x98, 0xa5, 0x6b, 0xe2, 0xd9, 0xcd, 0xac, 0x0a, 0xe7, 0x67, 0x86, 0x12, 0x07, 0x5d, 0x50, 0x83,
	0xae, 0x42, 0x31, 0x9c, 0x2d, 0x93, 0x21, 0x35, 0x1c, 0x28, 0xff, 0x19, 0x7e, 0x2a, 0x71, 0xd3,
	0x23, 0x12, 0x57, 0x52, 0x13, 0x87, 0x1f, 0x88, 0x6a, 0x6d, 0x9f, 0xed, 0xda, 0x71, 0xb5, 0xe6,
	0xa1, 0x40, 0xed, 0x40, 0xc4, 0x5c, 0x30, 0xf9, 0xa7, 0xa2, 0x3c, 0x91, 0x50, 0x7e, 0x28, 0x52,
	0x26, 0x95, 0x65, 0xca, 0xea, 0x50, 0xe4, 0x8d, 0x1a, 0x8c, 0xc8, 0x59, 0x28, 0x80, 0x77, 0x00,
	0xc9, 0x84, 0x73, 0x0b, 0xe7, 0xbc, 0xeb, 0xb9, 0x18, 0x3e, 0x82, 0x85, 0x84, 0x95, 0xf1, 0xee,
	0x13, 0xde, 0x8c, 0xab, 0xfe, 0x94, 0x28, 0x10, 0xa4, 0x2b, 0x2d, 0x95, 0xab, 0x8a, 0x22, 0x3b,
	0xa6, 0xa3, 0x07, 0x50, 0x39, 0xf0, 0xec, 0xd4, 0x94, 0xb9, 0xa8, 0xf2, 0x43, 0x40, 0xaa, 0xf2,
	0x98, 0xae, 0x17, 0xa0, 0xb2, 0x43, 0xba, 0x24, 0xe1, 0x1a, 0xdf, 0x07, 0xa4, 0x12, 0xa5, 0xc9,
	0x1a, 0x94, 0xb9, 0x4a, 0xc8, 0xb1, 0xe5, 0x85, 0x57, 0x49, 0xf8, 0x11, 0xac, 0xc7, 0xf9, 0xde,
	0x4f, 0x6f, 0x6a, 0x51, 0x5c, 0xbc, 0x1b, 0x05, 0x51, 0xac, 0x89, 0x9a, 0xec, 0xc6, 0x98, 0x82,
	0xf7, 0x00, 0x8f, 0x32, 0x32, 0x66, 0x7c, 0x2f, 0x00, 0xed, 0x51, 0xe7, 0x44, 0x1a, 0x52, 0x30,
	0xb8, 0x56, 0x9f, 0x1d, 0xef, 0x2b, 0x13, 0x5f, 0xa1, 0xa0, 0x6b, 0x30, 0x2b, 0x4e, 0x72, 0x3b,
	0xf4, 0x65, 0x5f, 0x25, 0x89, 0xbc, 0xbd, 0x12, 0xb6, 0xc7, 0x84, 0xb6, 0x04, 0xd5, 0x03, 0x67,
	0x18, 0x1c, 0xfe, 0x18, 0x16, 0x53, 0xf4, 0x31, 0x0d, 0x87, 0x65, 0x90, 0xda, 0x61, 0x22, 0xb3,
	0xcb, 0x30, 0x78, 0x14, 0xb4, 0xf4, 0xa3, 0x20, 0xcb, 0x90, 0x6b, 0x64, 0x6c, 0x48, 0x6b, 0x4f,
	0x08, 0x93, 0xbb, 0xef, 0x6e, 0xcf, 0xea, 0x90, 0x03, 0xaf, 0xeb, 0x5a, 0xf6, 0x81, 0xb9, 0x17,
	0x01, 0xaa, 0x41, 0xb9, 0xed, 0x3a, 0x8c, 0x38, 0x6c, 0xff, 0xcc, 0x8b, 0x1a, 0x43, 0x25, 0xe1,
	0x7b, 0x50, 0xcb, 0x37, 0x22, 0x01, 0xcd, 0x43, 0xa1, 0xef, 0xcb, 0x61, 0x66, 0xf2, 0xcf, 0xd6,
	0x2f, 0xf3, 0x50, 0xe6, 0x48, 0x9e, 0x13, 0xff, 0x15, 0x6d, 0x13, 0xf4, 0x15, 0x14, 0xc5, 0x1a,
	0x8a, 0x8c, 0x24, 0x5a, 0x75, 0xdb, 0x35, 0x96, 0x33, 0x79, 0xa1, 0x0f, 0x7c, 0xe5, 0xdb, 0xdf,
	0xff, 0xfe, 0x7e, 0xa2, 0x82, 0x67, 0xc4, 0xff, 0x54, 0x5e, 0xb3, 0xcb, 0xb9, 0x1f, 0x6a, 0x9b,
	0xa8, 0x0d, 0xf3, 0xe9, 0xfd, 0x12, 0xbd, 0x97, 0xb4, 0x94, 0xb3, 0xb2, 0x1a, 0xd7, 0xcf, 0x13,
	0x93, 0xbe, 0xff, 0x87, 0x08, 0xc0, 0x60, 0x4b, 0x44, 0x6b, 0x49, 0xbd, 0xa1, 0x65, 0xd5, 0xa8,
	0xe5, 0x0b, 0x48, 0x93, 0x55, 0x11, 0xce, 0x1c, 0x2e, 0x89, 0x70, 0x78, 0xb9, 0x78, 0x2c, 0xdf,
	0x69, 0x30, 0x97, 0xdc, 0x4b, 0xd0, 0x46, 0xca, 0x54, 0xd6, 0x5a, 0x69, 0x5c, 0x1b, 0x2d, 0x24,
	0x7d, 0xde, 0x10, 0x3e, 0xd7, 0xf1, 0x4a, 0xec, 0xb3, 0xd9, 0x23, 0xcd, 0x68, 0x7b, 0x6e, 0xb6,
	0x85, 0x16, 0x87, 0xf1, 0xb3, 0x96, 0x5e, 0x0e, 0xa3, 0xf5, 0x08, 0xdd, 0x1a, 0xe5, 0x29, 0xb5,
	0x0f, 0x1a, 0xb7, 0x2f, 0x26, 0x2c, 0xe1, 0xdd, 0x15, 0xf0, 0x6e, 0xe1, 0xeb, 0xa3, 0xe0, 0x35,
	0x8e, 0x7c, 0xb7, 0xd7, 0xe0, 0xbb, 0x22, 0x07, 0xfa, 0x83, 0x06, 0xd5, 0xac, 0x55, 0x09, 0xdd,
	0x4c, 0x57, 0x36, 0x77, 0x17, 0x33, 0x36, 0x2f, 0x22, 0x2a, 0x21, 0x36, 0x04, 0xc4, 0x1b, 0x18,
	0xcb, 0x26, 0x14, 0x20, 0x63, 0x84, 0x7e, 0xa8, 0xda, 0xf0, 0xb9, 0x0e, 0x87, 0xf7, 0x12, 0xa6,
	0xa3, 0x0d, 0x06, 0x5d, 0x4d, 0xba, 0x49, 0x6d, 0x64, 0xc6, 0x6a, 0x1e, 0x5b, 0x7a, 0x5e, 0x10,
	0x9e, 0x67, 0x51, 0x59, 0xf1, 0x8c, 0x8e, 0x84, 0xfd, 0xed, 0xb3, 0xdd, 0x9d, 0x2c, 0xfb, 0xea,
	0x0e, 0x91, 0x61, 0x3f, 0xb1, 0x25, 0xe0, 0x65, 0x61, 0x7f, 0x11, 0x2d, 0x0c, 0x92, 0x4f, 0xed,
	0xa0, 0xf9, 0x86, 0xda, 0xc1, 0x5b, 0xe4, 0x41, 0x59, 0x19, 0xe9, 0xa8, 0x96, 0x89, 0x55, 0xd9,
	0x19, 0x8c, 0xf5, 0x11, 0x12, 0xd2, 0xe1, 0x8a, 0x70, 0xb8, 0x84, 0xaa, 0x6a, 0x2a, 0xdf, 0x84,
	0xbb, 0xc5, 0x5b, 0x74, 0x08, 0xa5, 0x78, 0xb2, 0xa3, 0xec, 0xdc, 0xc4, 0xeb, 0x81, 0xb1, 0x96,
	0xcb, 0x4f, 0x5e, 0x36, 0x34, 0xa3, 0x76, 0x16, 0x3a, 0x06, 0x18, 0xcc, 0xf0, 0xf4, 0x9d, 0x1e,
	0x5a, 0x0d, 0xd2, 0x77, 0x7a, 0x78, 0xfc, 0x47, 0x4f, 0x54, 0x2b, 0xe1, 0x86, 0xf7, 0xc1, 0x21,
	0xc0, 0x60, 0xb4, 0xa7, 0x3d, 0x0d, 0x6d, 0x02, 0x69, 0x4f, 0xc3, 0x5b, 0x01, 0xae, 0x08, 0x4f,
	0xe5, 0xcd, 0xc1, 0xeb, 0x81, 0xbe, 0xd1, 0xc0, 0xc8, 0x1f, 0xe1, 0xa8, 0x99, 0x53, 0x91, 0xbc,
	0x8d, 0xc1, 0xb8, 0x73, 0x71, 0x85, 0xf8, 0x95, 0x7c, 0x0d, 0x65, 0x65, 0x84, 0xa6, 0xfb, 0x64,
	0x78, 0xea, 0xa6, 0xfb, 0x24, 0x63, 0xfe, 0xe2, 0x6b, 0x22, 0xd4, 0xd5, 0xd6, 0xff, 0x13, 0xaf,
	0x82, 0xfc, 0x21, 0xa9, 0xd9, 0xa5, 0xce, 0x09, 0xcf, 0xf0, 0x5b, 0x98, 0x4d, 0x8c, 0x6f, 0x84,
	0x53, 0xd5, 0xca, 0x98, 0xf9, 0xc6, 0xc6, 0x48, 0x19, 0xe9, 0x7f, 0x43, 0xf8, 0xbf, 0xda, 0x5a,
	0xce, 0xf4, 0xdf, 0x77, 0x38, 0x02, 0xfe, 0x0e, 0x19, 0xf9, 0x83, 0x3b, 0x23, 0xf9, 0xa3, 0xf7,
	0x84, 0x8c, 0xe4, 0x9f, 0xb3, 0x13, 0xa4, 0xee, 0xaf, 0x37, 0x00, 0xc8, 0x7b, 0xe3, 0x27, 0x0d,
	0xf4, 0xbc, 0x21, 0x8e, 0x1a, 0x43, 0xbe, 0x46, 0x6d, 0x0c, 0xc6, 0xd6, 0x45, 0xc5, 0x25, 0xb0,
	0x9b, 0x02, 0xd8, 0x06, 0x5a, 0x4f, 0xe4, 0xaf, 0x2f, 0xe4, 0x9a, 0xf2, 0xe7, 0xb8, 0x06, 0xe5,
	0xba, 0xdb, 0x73, 0x2f, 0x12, 0x3f, 0xbd, 0x1e, 0x4e, 0x89, 0x3f, 0xef, 0xff, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xbc, 0x7a, 0xa6, 0xae, 0x9d, 0x15, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshUserToken(ctx context.Context, in *RefreshUserTokenRequest, opts ...grpc.CallOption) (*RefreshUserTokenResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	ChangePasswordFromTemp(ctx context.Context, in *ChangePasswordFromTempRequest, opts ...grpc.CallOption) (*ChangePasswordFromTempResponse, error)
	RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetByIDs(ctx context.Context, in *GetByIdsRequest, opts ...grpc.CallOption) (*GetByIdsResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error)
	GetUserMe(ctx context.Context, in *GetUserMeRequest, opts ...grpc.CallOption) (*GetUserMeResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	GetUserByTwitterScreenName(ctx context.Context, in *GetUserByTwitterScreenNameRequest, opts ...grpc.CallOption) (*GetUserByTwitterScreenNameResponse, error)
	LinkTwitter(ctx context.Context, in *LinkTwitterRequest, opts ...grpc.CallOption) (*LinkTwitterResponse, error)
	UnLinkTwitter(ctx context.Context, in *UnLinkTwitterRequest, opts ...grpc.CallOption) (*UnLinkTwitterResponse, error)
	GetTwitterUserByScreenName(ctx context.Context, in *GetTwitterUserByScreenNameRequest, opts ...grpc.CallOption) (*GetTwitterUserByScreenNameResponse, error)
	GetProfileImageUploadURL(ctx context.Context, in *GetProfileImageUploadURLRequest, opts ...grpc.CallOption) (*GetProfileImageUploadURLResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RefreshUserToken(ctx context.Context, in *RefreshUserTokenRequest, opts ...grpc.CallOption) (*RefreshUserTokenResponse, error) {
	out := new(RefreshUserTokenResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/RefreshUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePasswordFromTemp(ctx context.Context, in *ChangePasswordFromTempRequest, opts ...grpc.CallOption) (*ChangePasswordFromTempResponse, error) {
	out := new(ChangePasswordFromTempResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/ChangePasswordFromTemp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error) {
	out := new(RequestPasswordResetResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/RequestPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByIDs(ctx context.Context, in *GetByIdsRequest, opts ...grpc.CallOption) (*GetByIdsResponse, error) {
	out := new(GetByIdsResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error) {
	out := new(GetUserByIdResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserMe(ctx context.Context, in *GetUserMeRequest, opts ...grpc.CallOption) (*GetUserMeResponse, error) {
	out := new(GetUserMeResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetUserMe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByTwitterScreenName(ctx context.Context, in *GetUserByTwitterScreenNameRequest, opts ...grpc.CallOption) (*GetUserByTwitterScreenNameResponse, error) {
	out := new(GetUserByTwitterScreenNameResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetUserByTwitterScreenName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LinkTwitter(ctx context.Context, in *LinkTwitterRequest, opts ...grpc.CallOption) (*LinkTwitterResponse, error) {
	out := new(LinkTwitterResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/LinkTwitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UnLinkTwitter(ctx context.Context, in *UnLinkTwitterRequest, opts ...grpc.CallOption) (*UnLinkTwitterResponse, error) {
	out := new(UnLinkTwitterResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/UnLinkTwitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetTwitterUserByScreenName(ctx context.Context, in *GetTwitterUserByScreenNameRequest, opts ...grpc.CallOption) (*GetTwitterUserByScreenNameResponse, error) {
	out := new(GetTwitterUserByScreenNameResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetTwitterUserByScreenName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetProfileImageUploadURL(ctx context.Context, in *GetProfileImageUploadURLRequest, opts ...grpc.CallOption) (*GetProfileImageUploadURLResponse, error) {
	out := new(GetProfileImageUploadURLResponse)
	err := c.cc.Invoke(ctx, "/discussproto.UserService/GetProfileImageUploadURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshUserToken(context.Context, *RefreshUserTokenRequest) (*RefreshUserTokenResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	ChangePasswordFromTemp(context.Context, *ChangePasswordFromTempRequest) (*ChangePasswordFromTempResponse, error)
	RequestPasswordReset(context.Context, *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	GetByIDs(context.Context, *GetByIdsRequest) (*GetByIdsResponse, error)
	GetUserById(context.Context, *GetUserByIdRequest) (*GetUserByIdResponse, error)
	GetUserMe(context.Context, *GetUserMeRequest) (*GetUserMeResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	GetUserByTwitterScreenName(context.Context, *GetUserByTwitterScreenNameRequest) (*GetUserByTwitterScreenNameResponse, error)
	LinkTwitter(context.Context, *LinkTwitterRequest) (*LinkTwitterResponse, error)
	UnLinkTwitter(context.Context, *UnLinkTwitterRequest) (*UnLinkTwitterResponse, error)
	GetTwitterUserByScreenName(context.Context, *GetTwitterUserByScreenNameRequest) (*GetTwitterUserByScreenNameResponse, error)
	GetProfileImageUploadURL(context.Context, *GetProfileImageUploadURLRequest) (*GetProfileImageUploadURLResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) RefreshUserToken(ctx context.Context, req *RefreshUserTokenRequest) (*RefreshUserTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshUserToken not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedUserServiceServer) ChangePasswordFromTemp(ctx context.Context, req *ChangePasswordFromTempRequest) (*ChangePasswordFromTempResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePasswordFromTemp not implemented")
}
func (*UnimplementedUserServiceServer) RequestPasswordReset(ctx context.Context, req *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (*UnimplementedUserServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedUserServiceServer) GetByIDs(ctx context.Context, req *GetByIdsRequest) (*GetByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDs not implemented")
}
func (*UnimplementedUserServiceServer) GetUserById(ctx context.Context, req *GetUserByIdRequest) (*GetUserByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedUserServiceServer) GetUserMe(ctx context.Context, req *GetUserMeRequest) (*GetUserMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMe not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) GetUserByTwitterScreenName(ctx context.Context, req *GetUserByTwitterScreenNameRequest) (*GetUserByTwitterScreenNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByTwitterScreenName not implemented")
}
func (*UnimplementedUserServiceServer) LinkTwitter(ctx context.Context, req *LinkTwitterRequest) (*LinkTwitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkTwitter not implemented")
}
func (*UnimplementedUserServiceServer) UnLinkTwitter(ctx context.Context, req *UnLinkTwitterRequest) (*UnLinkTwitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnLinkTwitter not implemented")
}
func (*UnimplementedUserServiceServer) GetTwitterUserByScreenName(ctx context.Context, req *GetTwitterUserByScreenNameRequest) (*GetTwitterUserByScreenNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTwitterUserByScreenName not implemented")
}
func (*UnimplementedUserServiceServer) GetProfileImageUploadURL(ctx context.Context, req *GetProfileImageUploadURLRequest) (*GetProfileImageUploadURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileImageUploadURL not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RefreshUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RefreshUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/RefreshUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RefreshUserToken(ctx, req.(*RefreshUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePasswordFromTemp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordFromTempRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePasswordFromTemp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/ChangePasswordFromTemp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePasswordFromTemp(ctx, req.(*ChangePasswordFromTempRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/RequestPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RequestPasswordReset(ctx, req.(*RequestPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByIDs(ctx, req.(*GetByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserById(ctx, req.(*GetUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetUserMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserMe(ctx, req.(*GetUserMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByTwitterScreenName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTwitterScreenNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByTwitterScreenName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetUserByTwitterScreenName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByTwitterScreenName(ctx, req.(*GetUserByTwitterScreenNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LinkTwitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTwitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LinkTwitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/LinkTwitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LinkTwitter(ctx, req.(*LinkTwitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UnLinkTwitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnLinkTwitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UnLinkTwitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/UnLinkTwitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UnLinkTwitter(ctx, req.(*UnLinkTwitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetTwitterUserByScreenName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTwitterUserByScreenNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetTwitterUserByScreenName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetTwitterUserByScreenName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetTwitterUserByScreenName(ctx, req.(*GetTwitterUserByScreenNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetProfileImageUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileImageUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfileImageUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discussproto.UserService/GetProfileImageUploadURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfileImageUploadURL(ctx, req.(*GetProfileImageUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discussproto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "RefreshUserToken",
			Handler:    _UserService_RefreshUserToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "ChangePasswordFromTemp",
			Handler:    _UserService_ChangePasswordFromTemp_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _UserService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "GetByIDs",
			Handler:    _UserService_GetByIDs_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _UserService_GetUserById_Handler,
		},
		{
			MethodName: "GetUserMe",
			Handler:    _UserService_GetUserMe_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUserByTwitterScreenName",
			Handler:    _UserService_GetUserByTwitterScreenName_Handler,
		},
		{
			MethodName: "LinkTwitter",
			Handler:    _UserService_LinkTwitter_Handler,
		},
		{
			MethodName: "UnLinkTwitter",
			Handler:    _UserService_UnLinkTwitter_Handler,
		},
		{
			MethodName: "GetTwitterUserByScreenName",
			Handler:    _UserService_GetTwitterUserByScreenName_Handler,
		},
		{
			MethodName: "GetProfileImageUploadURL",
			Handler:    _UserService_GetProfileImageUploadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
